### PR TITLE
mt3d modelgrid to inherit from modflow modelgrid

### PR DESCRIPTION
**Pull request by briochh**
I know that there has been a lot of work going on with the modelgrid related methods and properties so apologies if this is way out of line. 

I was wondering if it was intended for the mt3d modelgrid property to be inherited from the modflow modelgrid? 

I have made some changes to the `mt.modelgrid()` property definition in this PR. 
If this looks like it might be heading toward the intended behaviour, I'll add in a test to cover this off. If I am way wide of the mark, I am happy to close the PR and work out a workaround locally.

### CODE REVIEW

**Comment by jdhughes-usgs** [comment]
@spaulins-usgs and @jlarsen-usgs do you have any thoughts on this PR??

**Comment by spaulins-usgs** [comment]
Currently your PR changes ibound to be pulled from mt3d btn (rather than modflow dis) and changes the spatial reference parameters to be pulled from modflow (rather than mt3d). I think you are on the right track with pulling ibound from mt3d, but that everything should be pulled from mt3d for consistency. Could you change the code to pull the remaining model grid parameters (delc, delr, top, botm) from mt3d btn?

The spatial reference parameters (proj4, epsg, xoff, yoff, angrot) currently pull from mt3d (defined by kwargs passed in when initializing the mt3d object), while your change pulls them from modflow (defined the same way). Why do you want to pull the spatial reference parameters from modflow? For consistency we should probably continue pulling them from mt3d if we are going to be pulling everything else in the model grid from mt3d.

**Comment by briochh** [comment]
Are the spatial reference parameters ever written (or read) for an mt3d model? I was under the impression that that string was only written for the modflow model (in the .nam file). If there is read/write of the spatial reference string when loading and writing the mt3d model then that’s cool we can definitely just use them. 

I guess what I was trying to get towards here is whether, in the absence of any spatial reference info when loading mt3d, it makes sense to inherit the modflow model spatial reference information (as the modflow model can be passed when loading mt3d). I think it is safe to assume that mt3d and modflow instances of the same model would have consistent spatial references but maybe I’m missing something.

**Comment by jlarsen-usgs** [comment]
It makes sense to me to be able to pull the spatial reference information from a single location for exporting and plotting purposes instead of passing them in at multiple locations.  Where that location is and how to best implement it may be something we need to discuss further, but it seems to me that it'd be unlikely that a user would want MODFLOW to have one set of spatial reference parameters and then want MT3D to have a separate set of spatial reference parameters since the grids are defined by the same discretization. 

I believe that is also a potential issue for the Seawat class. It may be advantageous to discuss a full solution for the spatial reference interaction between the three classes.

**Comment by spaulins-usgs** [comment]
@briochh I don't think spatial reference parameters are read from the mt3d namefile, but they can be passed in as kwargs on construction of the mt3d object. I think the best behavior is to first use any spatial reference information defined when mt3d is initialized (as it currently behaves), and then use spatial reference information from modflow for any parameters that are not defined in mt3d. This could be done by adding code near the bottom of the "# resolve offsets" block of code right above the "set_coord_info" call. Something like this:

proj4 = self._modelgrid.proj4
if proj4 is None:
    proj4 = self.mf._modelgrid.proj4
...
<repeat for each spatial reference variable>
...
self._modelgrid.set_coord_info(xoff, yoff, ,angrot, epsg, proj4)

This will pull all spatial information from the modflow namefile but also allow you to define spatial information directly in the mt3d object, with the mt3d information taking precedence. Would this solution work for you?

**Comment by briochh** [comment]
@spaulins-usgs, I'm with you on that one and have added to the PR accordingly. It includes a bit of a fiddle to deal with `angrot` which I think defaults to 0. as soon as the Grid constructor is called. My solution is to inherit `angrot` from the modflow model if it exists, else, set to 0.0. 

I think that @jlarsen-usgs might have a point on all this though. Could we run into difficulty having different modelgrid objects floating around for these "chained" models? @jlarsen-usgs, I have not touched the Seawat class at the moment - I dont have much experience with that end of flopy - but I think you could add something similar in there? Maybe needing to squentially check the modflow and mt3d objects for their modelgrid spatial reference properties; I guess the question is what do you do if they all contain different information!?

**Comment by jlarsen-usgs** [comment]
@briochh My thought is that we could handle the Seawat class in a similar fashion to the mt3d class for the time being. Allow the user to set proj4 information through the keyword arguments, and if none are passed inherit them from the Modflow modelgrid object in a similar way to how @spaulins-usgs proposed for the mt3d class. 

This would also allow the user to specify spatial reference information in one location only (MODFLOW) and then if they needed to (I don't have an example case where they would need to) they can override it during the instantiation of the Mt3d or Seawat class.

**Comment by jlarsen-usgs** [comment]
@briochh I put together a solution for Seawat, since it interacts with the Modflow class differently. I'm opening a separate PR for it.

**Comment by briochh** [comment]
@jlarsen-usgs, I have attempted to address the Seawat part - including adding to the test. I'll add to my PR as there are a few other changes too but feel free to correct it!

**Comment by jlarsen-usgs** [comment]
@briochh, It looks like we took similar approaches, I just closed my PR to avoid conflicts with yours.

**Comment by jdhughes-usgs** [comment]
@jlarsen-usgs let me know if this is ready to merge.

@briochh is your test comparable to the test @jlarsen-usgs developed. Is there anything to add to your test?

**Comment by jlarsen-usgs** [comment]
@jdhughes-usgs This looks like it's ready to merge. The tests @briochh created are comparable to the one I had put together.

**Pull request merged**
