### PR TITLE
Fix quasi3d plotting

### PR DESCRIPTION
**Pull request by rubencalje**
In this pull request I tried to fix the plotting methods for quasi3d layers in regular modflow models. The bug and discussion can be found in issue #656  .

I tried to make as little changes as possible. I removed the nlay_nocbd-property of the StructuredGrid (as I think it is confusing), and set the nlay property of the StructuredGrid equal to that of the model. The plotting methods now plot everything in the aquifers, and the quasi3d-confining units are ignored for the most part (which I think is the right way).

An extra test is also added, to test a plot of a map and a cross section with one quasi-3d layer.

### CODE REVIEW

**Comment by rubencalje** [comment]
For some reason Python 3.6 is failing, but I do not think it is caused by my changes. All other builds are passing.

**Comment by langevin-usgs** [comment]
I restarted.  Let's see what Travis says.

**Comment by spaulins-usgs** [comment]
I see a potential problem with the changes to __init__ of structuredgrid.py.  The code:

            if nlay is None:
                self.__nlay = len(botm)
            else:
                self.__nlay = nlay

may not produce a consistent self.__nlay.  The nlay parameter passed into __init__ represents the total number of non-confining layers.  For example, mf.py passes self.dis.nlay to it, which does not include confining layers.  If nlay is passed in, self.__nlay will end up being the number of non-confining layers.  While if nlay is not passed in, self.__nlay will end up being len(botm), which includes confining layers.  If you intention is to always have self.__nlay include confining layers then the nlay parameter should be removed from __init__.

**Comment by rubencalje** [comment]
> I see a potential problem with the changes to **init** of structuredgrid.py. The code:
> 
> ```
>         if nlay is None:
>             self.__nlay = len(botm)
>         else:
>             self.__nlay = nlay
> ```
> 
> may not produce a consistent self.__nlay. The nlay parameter passed into **init** represents the total number of non-confining layers. For example, mf.py passes self.dis.nlay to it, which does not include confining layers. If nlay is passed in, self.__nlay will end up being the number of non-confining layers. While if nlay is not passed in, self.__nlay will end up being len(botm), which includes confining layers. If you intention is to always have self.__nlay include confining layers then the nlay parameter should be removed from **init**.

Thanks for your comment. My intention is that self.__nlay does not include confining layers anymore (just like the model). I do not fully understand when and how structuredgrid is called (except auomatically when adding a dis-file). In the current way, it is still possible to call structuredgrid with only supplying botm (for models without confining layers). If the user wants to include information about how many real layers there are for a model with confining layers, he should supply nlay as well.  I think this is the way the original code performed as well.

Now that nlay in structuredgrid does not include confining layers anymore, this can cause some problems in people's code, but I think it is more clear, and is also needed for the plotting methods to function properly. Please let me know if you disagree.

By the way, I just made another small commit, to make sure plot_discharge on a map also functions without supplying the head-argument.

**Comment by spaulins-usgs** [comment]
Okay I think I understand what you are trying to do.  If self.__nlay is now intended to not include confining layers, some additional code changes are needed.  For example, StructuredGrid has a xyzcellcenters method that creates an array of z values:

	z = np.empty((self.__nlay, self.__nrow, self.__ncol))
  
With your code changes this array will not include the confining layers.  xyzcellcenters then calculates the cell centers for each layer:

	z[0, :, :] = (self._top[:, :] + self._botm[0, :, :]) / 2.
	for l in range(1, self.__nlay):
		z[l, :, :] = (self._botm[l - 1, :, :] +
					  self._botm[l, :, :]) / 2.

Note that botm includes confining layers.  With your changes this code will not reach the bottom layers for models with confining layers.  Instead it will loop through nlay model layers while botm's z dimension is nlay + cbd.  The result will be an incomplete mix of confining and non-confining layers.  In order for xyzcellcenters to return only the non-confining layers it will need to check if the model contains confining layers.  If it does, it will need to filter out confining layers from botm.

I think xyzvertices has a similar problem.

**Comment by jlarsen-usgs** [comment]
@rubencalje 
I have a question about this? If I had a 4 layer model with quasi-3D confining layers under layer 1, layer  2, and layer 3. That will be represented by seven layers in the modelgrid, correct? If I decided to plot the all of the wells in layer 3 of the model in cross section, where would they show up? Would they be in the third cross-sectional layer, which would correspond to layer 2 or would they show up in the 5th cross-sectional layer (layer 5)? Same question for plotting and contouring arrays.

**Comment by rubencalje** [comment]
> @rubencalje
> I have a question about this? If I had a 4 layer model with quasi-3D confining layers under layer 1, layer 2, and layer 3. That will be represented by seven layers in the modelgrid, correct? If I decided to plot the all of the wells in layer 3 of the model in cross section, where would they show up? Would they be in the third cross-sectional layer, which would correspond to layer 2 or would they show up in the 5th cross-sectional layer (layer 3)? Same question for plotting and contouring arrays.

My commits are mainly to make sure this behaves ok. The wells will show up in the right layer (the same layer you put them in), as do the contours (if I did everything right). I added a test in the file t070_test_quasi3layers.py. This is for a three layer model with one quasi3d confing layer below the top layer. You can play with the numers for nlay, laycbd and the layer of the well (I did), and see that the plot_grid, plot_array, contour_array, plot_ibound, plot_bc and plot_discharge all perform as expected now, both in cross-section as in a map.

**Comment by rubencalje** [comment]
@spaulins-usgs 
I see your point, zcellcenters does not make any sense after my changes. I think we should keep the botm of the quasi-3d-confing layers in botm, otherwise we are not able to calculate the cell middle (vertically). In my opinion zcellcenters should only contain the centers of the aquifer layers, while zvertices should contain the top and botm of each layer, so these can be drawn ok. How are zcellcenters and zvertices use in flopy, besides drawing cross-sections?


I think we should supply laycbd to __init__ of structuredgrid, to determine which layers are quasi3d or not. Do you agree?

**Comment by spaulins-usgs** [comment]
@rubencalje 
I agree that it is better to have zcellcenters only contain the aquifer layers.  Supplying laycbd to __init__ as an optional variable, as you did, is a good implementation. 

zcellcenters is used by the netcdf exporting code, though I think it is better not to export the quasi-3d confining layers.   zvertices is only used by the plotting code.

**Comment by jlarsen-usgs** [comment]
> 
> My commits are mainly to make sure this behaves ok. The wells will show up in the right layer (the same layer you put them in), as do the contours (if I did everything right). I added a test in the file t070_test_quasi3layers.py. This is for a three layer model with one quasi3d confing layer below the top layer. You can play with the numers for nlay, laycbd and the layer of the well (I did), and see that the plot_grid, plot_array, contour_array, plot_ibound, plot_bc and plot_discharge all perform as expected now, both in cross-section as in a map.

@rubencalje that's great to hear and to see that you've tested these functions.

**Pull request merged**
