### PR TITLE
reading array data with free format

### PR DESCRIPTION
**Pull request by gyanz**
This implementation of load_txt behaves like MODFLOW while reading array data with free format. It reads the first "total column number" values, and ignores any comments at the end of each line.

### CODE REVIEW

**Comment by mwtoews** [comment]
Could you add an example of this type of array data to `flopy/autotest/t004_test_utilarray.py` (i.e. append to `test_load_txt_free`)?

**Comment by gyanz** [comment]
The following lines added to text_load_txt_free function passed the tests:
```
    a = np.array([[5,6],[7.1,1],[9,10],[1,2]], dtype=np.float32)
    fp = StringIO(dedent(u'''\
        5 6 row 1 layer 1
        7.1, +1E-00 row 2
        9 10 row 3
        1*1,2*2 row 4
    '''))
    fa = Util2d.load_txt(a.shape, fp, a.dtype, '(FREE)')
    np.testing.assert_equal(fa, a)
    assert fa.dtype == a.dtype
```

**Comment by gyanz** [comment]
The following lines added to text_load_txt_free function passed the tests:
```
    a = np.array([[5,6],[7.1,1],[9,10],[3,3]], dtype=np.float32)
    fp = StringIO(dedent(u'''\
        5 6 row 1 layer 1
        7.1, +1E-00 row 2
        9 10 row 3
        2*3 row 4
    '''))
    fa = Util2d.load_txt(a.shape, fp, a.dtype, '(FREE)')
    np.testing.assert_equal(fa, a)
    assert fa.dtype == a.dtype
```

**Comment by jdhughes-usgs** [comment]
This change is incorrect. The `u2drel` and `u2dint` subroutines used in MODFLOW can handle wrapped arrays for `(FREE)` arrays. For example, `u2drel` uses an implicit loop to read `(FREE)` arrays:

`READ(LOCAT,*) (A(J,I),J=1,JJ)`
 
The proposed `[0:ncol]` change only works for the basic case where wrapped arrays are not used.

**Comment by gyanz** [comment]
Joe,

Should not the `READ(LOCAT,*) (A(J,I),J=1,JJ)` move to new line once JJ values are read?

**Comment by jdhughes-usgs** [comment]
Yes MODFLOW will but you change parses [0:ncol] from a single line `line.split()[0:ncol]`.

In the [wrapped example](https://github.com/modflowpy/flopy/pull/463#issuecomment-468007889) `line` would have 3 entries not 4.

**Comment by mwtoews** [comment]
With free arrays, the only place a comment could possibly be is on the very last line after the expected number of items have been read. And this is already handled, but perhaps not tested. Otherwise READ essentially just takes a flattened array.

It's poor form, but you could even trick u2drel to read a transposed (3, 4) array as a (4, 3) array (and vice versa).

**Comment by gyanz** [comment]
This makes sense. For the wrapped case, however,  the comment could be placed at the end of each line. flopy does not support this. Please correct me if I am wrong.

**Comment by jdhughes-usgs** [comment]
That is correct. You could add a column counter to the loop and skip the trash on a line after `ncol` items are added to the array.

**Comment by langevin-usgs** [comment]
MODFLOW will NOT support this for a model with 4 columns and 3 rows:

```
1.0 1.0 1.0   comment
1.0           comment
1.0 1.0 1.0   comment
1.0           comment
1.0 1.0 1.0   comment
1.0           comment
```

But it WILL support this:

```
1.0 1.0 1.0
1.0           comment
1.0 1.0 1.0
1.0           comment
1.0 1.0 1.0
1.0           comment
```

**Comment by gyanz** [comment]
I have incorporated column counter to the loop so that the function works with both wrapped and unwrapped arrays. First ncol items are read for a row, and remaining data in the line is ignored as comment. Should I reissue the pull request?

**Comment by mwtoews** [comment]
@langevin those examples are correct.

My previous comment was incorrect as `READ(LOCAT,*) (A(J,I),J=1,JJ)` does consider dimensions (and not a flattened array).

**Comment by jdhughes-usgs** [comment]
Just commit the change to your fork and the pull request will be updated. Like @mwtoews suggest it would be good to include a test. One like @langevin-usgs [comment](https://github.com/modflowpy/flopy/pull/463#issuecomment-468055345) array examples would be good.

**Comment by gyanz** [comment]
I made revisions in my fork via github instead of git. These changes are not visible to this pull request. Any suggestion on how to correct this?

**Comment by mwtoews** [comment]
@gyanz it looks like you need to push these to `gyanz:patch-1` instead of `gyanz:develop`. You can use `git cherry-pick` for this scenario (there are a few methods).

**Comment by jdhughes-usgs** [comment]
@gyanz rather than create a new array (`col_item`) couldn't this be done by just adding a column counter (`jdx`) that increments based on the items added and resets when the a row is complete. This is complicated for the `*` item.

**Comment by gyanz** [comment]
@jdhughes-usgs  How about the following implementation?
```
            if npl == 'free':
                col_cnt = 0
                while True:
                    if ',' in line:
                        line = line.replace(',', ' ')
                    col_data = line.split()
                    col_cnt += len(col_data)
                    if '*' in line:  # use slower method for these types of lines
                        for item in col_data:
                            if '*' in item:
                                num, val = item.split('*')
                                # repeat val num times
                                col_cnt += (int(num)-1)
                                items += int(num) * [val]
                            else:
                                items.append(item)
                    else:
                        items += col_data

                    if col_cnt < ncol:
                        line = file_in.readline()
                    elif col_cnt > ncol:
                        items = items[0:(ncol-col_cnt)]
                        break
                    else:
                        break
```

**Comment by gyanz** [comment]
In my proposed alternative,  `items = items[0:(ncol-col_cnt)]` could be expensive though.

**Comment by langevin-usgs** [comment]
This PR is dangling so I'm closing for now.  If anyone is interested in pursuing, feel free to open again.

**Pull request closed without merging**
