### PR TITLE
fix(get-modflow): fix code.json handling

### PR DESCRIPTION
**Pull request by w-bonelli**
The recent addition of `code.json` to the [`executables` repo distribution](https://github.com/MODFLOW-USGS/executables/releases/tag/9.0) seemed to trip up executable naming/suffix handling when `--subset` is provided. This PR fixes that and makes `--subset` work by exact rather than substring matching, so the user must specify e.g. `mfnwt` and `mfnwtdbl` separately to get both. ~~Also sets execute permissions on the `libmf6` shared library.~~

### CODE REVIEW

**Comment by mwtoews** [comment]
Any reason why to set executable permission on libmf6? Normally these are not executable, e.g. `./libmf6.so` shows "Segmentation fault (core dumped)"

**Comment by jdhughes-usgs** [comment]
@w-bonelli is this ready to be merged?

**Comment by w-bonelli** [comment]
Moved the execute permissions change on `libmf6` out of this PR to unblock and fix CI tests

**Comment by w-bonelli** [comment]
No longer directly relevant to this PR, but after testing `modflowapi` again it seems [execute permissions are no longer needed on `libmf6`](https://github.com/w-bonelli/modflowapi/actions/runs/3643178372). I was not able to identify the cause of the original issue.

**Review by jdhughes-usgs — APPROVED** [review]

**Pull request merged**
