### PR TITLE
feat(get/set data record): Updated get_data/set_data functionality and new get_record/set_record methods

### PR DESCRIPTION
**Pull request by spaulins-usgs**
New feature for MFArray and MFList data objects.  These objects now have get_record and set_record methods that allow the user to get a set data including the data's settings (filename, binary, factor, iprn).  Behavior of set_data has been changed to set data without changing the data's settings, except when set_data is passed a dictionary containing filename, binary, factor, or iprn, in which case it gives a deprecation warning and sets the data and the data's settings.

### CODE REVIEW

**Comment by langevin-usgs** [comment]
@spaulins-usgs, we probably need to do quite a bit of documenting for this new capability.  Are there plans to add that to this PR?

**Review by jdhughes-usgs — COMMENTED** [review]
A few issues with this PR:

1. The PR message does not really convey the changes. I find use of "metadata" confusing.
2. It would be nice if the testing of the `get_data` `set_data` capabilities were not imbedded within an already too long test. I would suggest having a specific test that works with a small test model and probably in a separate test file for mf6 core functionality.
3. I wish you could get to values with a `.` (like `blah.iprn`) instead of with a `["iprn"]`
4. I do not think the PR should be accepted without documentation on how to do to get a set values. Maybe a brief tutorial based on the autotest.

**Comment by spaulins-usgs** [comment]
@langevin-usgs, @jdhughes-usgs, I will then update the existing tutorials, "Working with MODFLOW List Data" and "Working with MODFLOW Grid Array Data" to reflect these changes.  

@jdhughes-usgs, I changed the PR message.  Hopefully it is less confusing now.  I am now working on moving the testing to a new test.  Regarding getting values with "." (as attributes of an object), I am not convinced that is better than the way it works now.  There is some precedent for getting values/settings/metadata in a dictionary, for example JSON.  Most python developers are already familiar with data/metadata in this format.  Also note that this format is already supported by flopy for constructing new data with filename/binary/iprn/factor settings.

**Comment by jdhughes-usgs** [comment]
@spaulins-usgs I might suggest a smaller specific tutorial rather than add it to an existing tutorial. @langevin-usgs not sure if you agree?

**Comment by spaulins-usgs** [comment]
@jdhughes-usgs Another option is to modify the "MODFLOW 6: Data Storage Information - How and Where to Store MODFLOW-6 Data" tutorial.  This is a short tutorial that already focuses on setting the data records (filename, binary, factor, iprn) when building packages.   I could add a few examples of getting and setting data records with get_record and set_record and this tutorial would still be one of our shortest tutorials.

**Comment by spaulins-usgs** [comment]
@jdhughes-usgs @langevin-usgs I have made the requested changes (1, 2, and 4) and the PR is ready to go.  I will merge the PR shortly unless I hear otherwise.

**Pull request merged**
