### PR TITLE
convert transient array data in UZF package to Transient2d

### PR DESCRIPTION
**Pull request by aleaf**
* bug fix for SFR package loading of transient stress period data (8599b73)
* fix `SpatialReference.write_gridSpec() so that origin units are same as grid spacing units
* shorten shapefile int field sizes to 18 (signed 64 bit int); otherwise they might be interpreted as floats on load of the shapefile

### CODE REVIEW

**Comment by jdhughes-usgs** [comment]
flopy3_uzf_example.ipynb need to be updated

**Comment by jdhughes-usgs** [comment]
There is still a problem with flopy3_uzf_example.ipynb reading UZFtest2.uzfcb2.bin. Does the notebook work for you?

**Comment by aleaf** [comment]
Yeah, it works for me. I switched the write path to temp to be like the other Notebooks, but that shouldn't make a difference. Is the m.run_model() causing the index error in opening the CBB? I have been running the model manually at the command line because my NWT executable is called 'mfnwt'. Is there a certain executable name that needs to be used with Travis?

**Comment by jdhughes-usgs** [comment]
We are building mfnwt version 1.1.3 on travis. What version of mfnwt are you using?

**Comment by aleaf** [comment]
Joe, does the `flopy3_uzf_example.ipynb` run locally for you? The CBB index error is still failing in Travis. Besides the modifications to UZF, there is also a bug fix to SFR (8599b73) where it wasn't reading stress period data with less than the total number of segments listed.

**Comment by langevin-usgs** [comment]
Andy, I fixed that t009_test script.  I think its best if we require a np.dtype instance to be passed into create_empty_recarray.  I think most things are passing now except a MODFLOW 6 issue.  Can you update this pull request?

**Comment by aleaf** [comment]
everything passes for me locally now, except `t505_test.test028_sfr`

**Comment by jdhughes-usgs** [comment]
I was thinking of pulling this in and trying to fix the uzf notebook that is failing on travis. Andy what to you think?

**Comment by aleaf** [comment]
I did just fix the reference to the cbb file in the uzf notebook (changed it while troubleshooting and forgot to switch it back).

**Comment by fahadkhan469** [comment]
Hi all!

I wanted to use the "flopy3_uzf_example.ipynb" file, but I cannot open it from GitHub. Also, I cannot get it to run locally. Can anyone help?

**Comment by langevin-usgs** [comment]
Looks like an image file was missing.  It may work now, but I've been noticing that nbviewer has been having a hard time rendering out notebooks on github.

**Comment by fahadkhan469** [comment]
image

No it still doesn't work. It was fine a couple of weeks ago.

**Comment by langevin-usgs** [comment]
I think that is a GitHub problem.  I am able to open the notebook just fine on my local machine using jupyter notebook.

**Comment by fahadkhan469** [comment]
Okay. Would it be possible for you to send me just a pdf copy of the notebook? My email is: 

fahad.khadim@uconn.edu

Thanks!

**Comment by fahadkhan469** [comment]
Nevermind it works now. I just updated my notebook.

thanks!

**Pull request merged**
