### PR TITLE
Resolve UnboundLocalError with crs property

### PR DESCRIPTION
**Pull request by mwtoews**
Identified a bug while exporting a netCDF file where a `UnboundLocalError` was raised for `datum` and/or `ellps`.

### CODE REVIEW

**Comment by mwtoews** [comment]
On further review, there is a similar `CRS` class within `export.shapefile_utils` with the same bug. Note that `reference.crs` is not marked as deprecated, but I expect that it is.

**Comment by mwtoews** [comment]
Should `reference.crs` be marked deprecated? I can add this to the PR if that was intended.

**Comment by langevin-usgs** [comment]
@mwtoews, in general we are moving toward deprecating flopy.utils.reference, so please feel free to mark reference.crs as deprecated.  Can you also check why that notebook is failing?  It didn't fail last time (I think) but I'm not sure why any of these changes would cause it to fail.

**Comment by mwtoews** [comment]
(opps, force-pushed on the wrong branch)

**Comment by mwtoews** [comment]
While switching tests from `reference.crs` to `shapefile_utils.CRS`, I found another bug from a typo (`spheriod_name` -> `spheroid_name`), also fixed here.

The unrelated notebook fail was fixed by a more recent PR from @jlarsen-usgs

All set to merge.

**Pull request merged**
