### PR TITLE
feat(raster): add option to extrapolate using ``nearest`` method

### PR DESCRIPTION
**Pull request by jdhughes-usgs**
Added `extrapolate_edges` option to `resample_to_grid` method to use
`nearest` interpolation method to fill cells outside data bounds. This
option results in an array that is completely filled with data (no nans).

### CODE REVIEW

**Review by jlarsen-usgs — CHANGES_REQUESTED** [review]
@jdhughes-usgs ,

the code changes look good. The only things that should be updated are in the Notebook.

1) The input parameter documentation for `resample_to_grid()` still shows xc and yc as inputs. These should be removed and changed to modelgrid (this is something I missed last time I updated the code). 

2) The notebook should be run from start to end again. It looks like the median sampling example was run after the vertex grid example and is showing cropped results when there was no cropping applied previously in the notebook.

**Comment by jdhughes-usgs** [comment]
@jlarsen-usgs there is something going on with the multi-threading in the notebook. `RuntimeError: can't start new thread` is issued in the notebook for the cell with

```
dem_data = rio.resample_to_grid(ml.modelgrid,
                                band=rio.bands[0],
                                method="median",
                                multithread=True,
                                thread_pool=8
                               )
```

I ran it on mac, linux, and windows and had the same problem. Not sure what the issue is but thought you should take a look to confirm that it just isn't an issue for me. Let me know.

**Comment by jlarsen-usgs** [comment]
@jdhughes-usgs 

I'll take a look at it and try to recreate the issue/debug it on a couple of my comupters. It might be the the `thread_pool` parameter is set too high and it can't start all of the threads on the machine(s) you're using.

**Comment by jdhughes-usgs** [comment]
@jlarsen-usgs I get the same error with `thread_pool=1`

**Comment by jlarsen-usgs** [comment]
@jdhughes-usgs 

I've found a couple of solutions to this issue. It looks like a jupyter specific conflict in how/when threads are created. It seems like making these "daemon" threads fixes it. I'll run some more tests and then push the changes if it doesn't break anything.

**Comment by jdhughes-usgs** [comment]
@jlarsen-usgs great. Do you want me to make a specific issue for this?

**Comment by jlarsen-usgs** [comment]
@jdhughes-usgs Either an issue or I could reference back to this discussion from my PR.

**Comment by jdhughes-usgs** [comment]
@jlarsen-usgs better to just reference back to the PR

**Pull request merged**
