### PR TITLE
feat(geospatial_util): geospatial consolidation utilities

### PR DESCRIPTION
**Pull request by jlarsen-usgs**
*Added GeoSpatialUtil for geospatial conversions

*Added GeoSpatialCollection for batch conversion of "Collection" objects

*Updated geometry.py and added additional geometry types to geometry.py

*updates to gridgen, shapefile_utils, triangle, rasters, and gridintersect modules that allow the user to supply any supported shape object to these geospatial methods. Supported shape objects are, geojson, shapely, shapefile, flopy.utils.geometry, and lists of vertices.

*Added t074_test_geospatial_util.py

issue #772

### CODE REVIEW

**Review by dbrakenhoff — APPROVED** [review]
This looks really good, I look forward to using this functionality! And thanks for implementing a general `intersect` method, that has been on my to-do list for while. 

Not really important, but I think the gridintersect tests can be simplified to only use the general `intersect` method as opposed to testing both the general method and the specific methods (i.e. `intersect_linestring`)?

**Comment by jlarsen-usgs** [comment]
@dbrakenhoff would it make sense to remove the `intersect_linestring`, `intersect_polygon`, and `intersect_point` methods, because there is now a general `intersect` method that routes the geometry to the proper hidden methods?

**Comment by dbrakenhoff** [comment]
Yea, I think it makes sense to remove those methods. Theyre unnecessary now and that would simplify things.

**Comment by jlarsen-usgs** [comment]
@dbrakenhoff I'll remove those methods, update the gridintersect tests, and any examples then.

**Comment by jlarsen-usgs** [comment]
@dbrakenhoff updates to gridintersect and the example are complete

**Comment by jlarsen-usgs** [comment]
the failure on python 3.6 ubuntu seems to be related to PR #1003

**Review by dbrakenhoff — APPROVED** [review]

**Review by aleaf — APPROVED** [review]
Hey @jlarsen-usgs, thanks for putting the effort into this. I think this looks good, and like the concept of using the geo interface to translate between the different formats. My only question is how well it scales. Have you tried it out with a larger grid (e.g. 1 million cells)? Maybe it's fine, just a thought of what might be a potential issue.

**Comment by jdhughes-usgs** [comment]
@jlarsen-usgs could you pull in the latest develop to see if it fixes the issue with python 3.6 on ubuntu?

**Pull request merged**
