### PR TITLE
Fixes: #603, #606, #614, and #616

### PR DESCRIPTION
**Pull request by spaulins-usgs**
Fixes reading/writing disu jagged arrays (#603), problem with ja array not being read property (#606), loading models with multiple wel packages (#614), and exporting transient2d objects to shapefiles (#616).

### CODE REVIEW

**Comment by langevin-usgs** [comment]
@spaulins-usgs, you want to update and retry?

**Comment by spaulins-usgs** [comment]
@langevin-usgs PR updated and build is now passing.

**Comment by langevin-usgs** [comment]
@spaulins-usgs, for some reason all the MODFLOW 6 package source files look like every line has changed.  I assume it is due to line endings.  Can you see if there is a way to fix that somehow?

**Comment by spaulins-usgs** [comment]
Yes the difference is due to line endings. I have updated the files to correct this.

The most recent version of these files have only <LF> line endings while the ones from my PR have <CR><LF> line endings. All of these files had <CR><LF> line endings and were switched to <LF> endings when release 3.2.12 was tagged. Was this intentional?

I just sampled about 30 flopy for mf2005 files and about 2/3 of them have <CR><LF> line endings and the remaining 1/3 have <LF> line endings. Is this something we want to keep consistent?

**Comment by spaulins-usgs** [comment]
@langevin-usgs The PR is ready to go. Though Travis failed after I checked in the files with only LF line endings, it only failed on 2.7 and it looks like the failure has nothing to do with the files I checked in.

**Comment by langevin-usgs** [comment]
Travis finally decided to let this pass.  Still lots of issues with Python 2.7 that seem to be primarily with Popen.  The suggestion is to not make any calls to run_model if it is Python 2.7 so that at least the basic flopy IO is tested with 2.7.

**Comment by langevin-usgs** [comment]
@spaulins-usgs, there is a lot in this PR.  Please try to update the wiki (https://github.com/modflowpy/flopy/wiki/FloPy-version-3.2.13-release-candidate-changes) and close the issues related to this.  Thanks!

**Pull request merged**
