### PR TITLE
fix(array3d_export): fix exporting of array3d to shp

### PR DESCRIPTION
**Pull request by martclanor**
This PR aims to address the issue raised in discussion https://github.com/modflowpy/flopy/discussions/2308

- [x] fix(MultiList): increment index per layer in build_list
- [x] fix(array3d_export): fix case for disu grid
- [x] add tests

### CODE REVIEW

**Comment by wpbonelli** [comment]
@martclanor the CI failures are unrelated and need not prevent this from merging if/when it's ready

**Comment by martclanor** [comment]
Thank you for clearing that out! I think it's ready for review.

**Review by wpbonelli — APPROVED** [review]
Thanks for wading in and fixing this @martclanor!

**Comment by wpbonelli** [comment]
The CI failures are due to https://github.com/actions/runner-images/issues/10624. MF6 nightly build is broken for the same reason. I will wait to see if github fixes the mac runner image before trying to work around it.

**Comment by wpbonelli** [comment]
The runner issue has been fixed upstream

**Pull request merged**
