### PR TITLE
fix(array): getting array data (#1028)

### PR DESCRIPTION
**Pull request by spaulins-usgs**
Getting array data (<data object>.array) fixed so that empty stress periods repeat data from the last previous stress period with data. If there is no previous stress period with data, None is used for MFDataList arrays and an array of zeros is used for MFDataArray arrays.

### CODE REVIEW

**Comment by spaulins-usgs** [comment]
@langevin-usgs As I fixed the .array method to work correctly with stress period data, there were a couple of decisions I had to make.  Empty stress period data occurs if there is no entry for the that stress period or any of the previous stress periods.  For empty stress periods I include None in the array for MFListData and include all zeros in the array for MFArrayData.  I thought about including an array of NaN values for MFArrayData, but NaN is not supported for integer data and we do have integer arrays.  Does my implementation seem reasonable or can you think of a better way to represent empty data in the array?

**Comment by langevin-usgs** [comment]
@spaulins-usgs, if I understand you correctly, we are trying to determine what to do with .array for a case similar to the one below.  What should .array do for periods 1 to 9 and what should it do for periods 11 to 14.  And should the behavior be different for periods 1 to 9 and periods 11 to 14?   I guess another important question is should mfarray and mflist behave differently?  Maybe we should chat about this.

```
BEGIN PERIOD 10
  ...some data
END PERIOD

BEGIN PERIOD 15
...some data
END PERIOD
```

**Comment by spaulins-usgs** [comment]
@langevin-usgs Yes those are the questions I am asking with this proposed fix.  For this PR periods 1 to 9 of your example would be filled with "empty" values, while periods 11 to 14 would be filled with the same data is period 10.  If there is another solution you are considering we should discuss.

**Comment by langevin-usgs** [comment]
@spaulins-usgs, is the .array return for periods 1 through 9 the same for mflist and mfarray?

**Comment by spaulins-usgs** [comment]
No, the .array contains None values for the MFList and contains 0 or 0.0 (depending on integer vs float) for the MFArray.  The .array data from an MFList is returned as a list of numpy recarrays while the .array data from an MFArray is returned as a single numpy ndarray.  Given this, I am not sure what single value would make sense for both.

**Comment by spaulins-usgs** [comment]
@langevin  FloPy now handles empty stress periods more consistently with MF6 behavior.  For transient lists, .getdata() returns None when no block exists for a given stress period, and [] where an empty stress period block exists.  

For transient lists, .array returns the data as MF6 interprets it.  It returns None if there is no data to be applied to that stress period (either an empty stress period block or no data before or up to that stress period), and otherwise returns the data to be applied to that stress period.

For transient arrays .getdata() returns None when no data is entered for a given stress period or when an empty stress period block exists, otherwise it returns the data. I tested MF6’s behavior for empty block data and it always keeps the value from the last stress period, which is different from MF6’s behavior with transient list data, thus the different .getdata() behavior in flopy.  By the way, when I say empty block data I mean empty for the particular data set.  In the transient arrays case stress period data can contain multiple data sets in the same block.

For transient arrays .array returns the data as MF6 interprets it.  In the case of no data being entered for the first n stress periods, those stress periods contain an array of 1’s if it is an integer (irch) and 0.0’s if it is a float (rch).  This should be consistent with how MF6 interprets empty array data.  Note that for the evta package I was able to verify that rate defaults to 0.0, but I am assuming that surface and depth also default to 0.0.  I was unable to confirm surface and depth since PRINT_INPUT does not print surface and depth to the listing file unless they are explicitly defined.  However, they must be defined to something since EVT shows up as removing water in the budget.  Is this a bug in how MF6 writes to the listing file or as designed?

**Review by langevin-usgs — APPROVED** [review]

**Pull request merged**
