### PR TITLE
Added zonbud_utils notebook example and modified write_zonfile.

### PR DESCRIPTION
**Pull request by jbellino-usgs**

### CODE REVIEW

**Comment by langevin-usgs** [comment]
Jason, I was looking at this quickly and I have a comment.  Do you think that your zonebudget utility can be just a function call that returns a recarray?  Right now, you first create the zone file and then you call the zonebudget routine, and the you load the csv.  Would it make sense to do this all in one shot?

**Comment by jbellino-usgs** [comment]
Hey Chris, yeah sure, that would be easier for the user if it was just one call. I'll work on a little update to do that.

**Comment by jbellino-usgs** [comment]
Do you guys have a preference for whether the budget items are signed so that all inflows are positive and outflows are negative or should they just match the zonbud output?

**Comment by jbellino-usgs** [comment]
Closing this pull request. Merged branch and will package into a single utility file and 1 pull request.

**Pull request closed without merging**
