### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by aleaf**
replaced RIV check in pakbase with customized check in mfriv, including check of rbot and stage vs. rbot.

Most or all of the BC packages have checks in common (NaNs, invalid indices, inactive cells, elevations below model bottom). It would be nice to be able to house these in pakbase, and then have package-specific checks in the individual packages. I implemented this in mfriv using super() to call the pakbase check() first, and then copy the results over to a new check instance for mfriv. Does anyone see any problems with this approach?

### CODE REVIEW

**Comment by jdhughes-usgs** [comment]
Could you pull the latest develop into yours. Hopefully, should be able to merge directly.

**Comment by jdhughes-usgs** [comment]
Not sure why this is failing. Can you run all of the autotests on your machine successfully?

**Comment by langevin-usgs** [comment]
Andy, it looks like you have added some new checks.   Can you make sure that you update checks.md to reflect this changes? Apologies if you've already done so.

**Comment by jdhughes-usgs** [comment]
Could you also move checks.md into the docs directory. I will add a link to the document from README.md. Is the visualization stuff a wish list or checks that have been implemented?

**Comment by aleaf** [comment]
Will do. Some of the things on there are ideas (actually, it would be great if people could contribute ideas). To clarify I will switch the format to a table that show what is implemented and where.

**Comment by jdhughes-usgs** [comment]
Sounds good.

**Pull request merged**
