### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by aleaf**
#### NetCDF export
* added module/class to fetch model metadata from ScienceBase.gov  
    * json files with variable long name descriptions and units  
    * MANIFEST.in file for including non-python files in setup.py install  
#### `SpatialReference`
* added automatic reading of spatial reference info from usgs.model.reference  
* `length_multiplier` that scales model grid in transforming to real coordinates is now inferred by `SpatialReference` from crs and model units, or can still be argued explicitly  
* fixed bug with dynamic setting of `SpatialReference` parameters  
* inverse option added to `SpatialReference.transform()`  
* demo notebook  

#### NWT
* 	forgive missing value for MXITERXMD  

#### MNW2
* fix bug where ztop and zbotm were written incorrectly in get_allnode_data(). This was not affecting writing of these variables, only their values in this summary array.

### CODE REVIEW

**Comment by jdhughes-usgs** [comment]
Can you change ```netcdf4!=1.2.8``` to ```netcdf4!<1.2.8``` in ```requirements.travis.txt``` and ```requirements33.travis.txt```? This should fix the failure.

**Comment by jdhughes-usgs** [comment]
I had a typo. Should be ```netcdf4<1.2.8``` not ```netcdf4!<1.2.8```

**Comment by aleaf** [comment]
That didn't seem to work. I'm having trouble reproducing these failures locally on either my windows or osx machines.

**Comment by aleaf** [comment]
I'm not entirely sure what was causing inequalities on the spatial reference tests, but it appears to be related to delr and delc being np.float32, python >= 3.5 and possibly numpy. The only test that fails now appears to be another inequality in the zonebudget module. @jbellino-usgs, might be a similar issue.

**Comment by aleaf** [comment]
Is there a way to see what version of numpy (or any other package for that matter) is being used in each Travis job? I'm not seeing it anywhere and it could help speed troubleshooting.

**Comment by langevin-usgs** [comment]
I added a command to the travis file to print the numpy version.  It looks like version 1.13 is being used now on Travis; conda is still only updating to 1.12.  Everything is failing at the moment with a variety of different errors.  Will need to look into this more this week.

**Comment by jbellino-usgs** [comment]
Good to know, thanks for the update. I'm working on another batch of commits to add a "net" keyword arg to the zonebudget stuff. Will wait to push...

**Pull request merged**
