### PR TITLE
adding multiple timeseries using ts.append_package()

### PR DESCRIPTION
**Pull request by OnnoEbbens**
I tried to add 3 timeseries to one package using this code (based on the example notebook `flopy3_mf6_obs_ts_tas`):
```
# initialize time series
ghb.ts.initialize(filename='tides.ts', timeseries=ts_data,
                  time_series_namerecord='tides',
                  interpolation_methodrecord='linearend', 
                  sfacrecord=1.1)
# append additional time series
ghb.ts.append_package(filename='wls.ts', timeseries=ts_data2,
                      time_series_namerecord='wl',
                      interpolation_methodrecord='stepwise', 
                      sfacrecord=1.2)

# append additional time series
ghb.ts.append_package(filename='test3.ts', timeseries=ts_data3,
                      time_series_namerecord='test3',
                      interpolation_methodrecord='stepwise', 
                      sfacrecord=1.3)
```
When I write this package to the .ghb file the second time series is not included, the ghb package looks like this:
```
BEGIN options
  BOUNDNAMES
  PRINT_INPUT
  PRINT_FLOWS
  SAVE_FLOWS
  TS6  FILEIN  tides.ts
  TS6  FILEIN  test3.ts
END options
```
while I expected this:
```
BEGIN options
  BOUNDNAMES
  PRINT_INPUT
  PRINT_FLOWS
  SAVE_FLOWS
  TS6  FILEIN  tides.ts
  TS6  FILEIN  wls.ts
  TS6  FILEIN  test3.ts
END options
```
The problem is that when you use the `ghb.ts.append_package` method it takes the first record in `ghb.ts._filerecord` and appends the new record to this. If there are already multiple records in `ghb.ts._filerecord` the other records are ignored. The proposed changes will solve this. I also added this to the `flopy3_mf6_obs_ts_tas` notebook.

### CODE REVIEW

**Comment by langevin-usgs** [comment]
Restarted.

**Comment by langevin-usgs** [comment]
Looks like this notebook is failing for some reason.  Any ideas?

**Comment by spaulins-usgs** [comment]
Not sure. What is the difference between Travis run type "misc" and run type "test"? It is passing on python 3.7 with run type "test" but failing with run type "misc".

**Comment by langevin-usgs** [comment]
misc is running the notebooks.  I don't think the notebooks run on the other configurations.

**Comment by OnnoEbbens** [comment]
It might be because I ran the notebook and thus changed the kernel settings of the notebook. I revert these changes in my latest commit.

**Pull request merged**
