### PR TITLE
feat(optionblock): New feature optionblock to address NWT-11 Options

### LINKED ISSUE #247: SFR2 options (e.g. reachinput) for mfnwt
mfnwt does not support SFR options (such as reachinput) on one line and would prefer something as follows:
options
reachinput
end

I have made a personal work around to the load and write functions of SFR (attached).  Feel free to use it, or make a more comprehensive version.
[sfr_modification.txt](https://github.com/modflowpy/flopy/files/1291087/sfr_modification.txt)

### PR DESCRIPTION
**Pull request by jlarsen-usgs**
New feature optionblock.OptionBlock added to flopy.utils to handle option read/write/and editing for option lines and option blocks within flopy. OptionBlock implemented for ModflowWel, ModflowSfr2, and ModflowUzf1. Added unit tests to t034_test.py.

fix #247

### CODE REVIEW

**Comment by langevin-usgs** [comment]
@jlarsen-usgs, looks like there is a lot of good stuff in here.  But I also see changes that probably shouldn't go in this pull request.  Can you look through this and remove anything that is just chatter.  We want to make sure that the pull request consists of just the meat of things that needs to be changed. For example, here you are commenting out different tests.  And unless there are no actual changes to the notebook content, then there probably is no need to include them in the PR.  

screen shot 2019-02-05 at 5 09 39 pm

**Comment by jlarsen-usgs** [comment]
@langevin-usgs . I went through and cleaned up the chatter that is not relevant to this PR.

**Comment by langevin-usgs** [comment]
Thanks, @jlarsen-usgs, that looks much better.  I'm looking at Travis and it looks like some of the notebooks are failing in the Python 3.6 tests.  I'm not sure why, and I'm not sure why Travis didn't fail.  I'm not sure it is related to this pull request or not.  Does it all run locally on your end?

**Comment by jlarsen-usgs** [comment]
@langevin-usgs, I've been checking out the Notebook failures.

1) flopy3_mt3d-usgs_examples.ipynb was crashing due to an edge case with the OptionBlock. I am testing the fix for this. 

2) flopy3_nwt_options.ipynb needs a platform check to run on linux/mac. It was looking for "mfnwt.exe" instead of "mfnwt" on travis. I've taken care of this and it should run on linux\mac now.

3) flopy3_modpath7_create_simulation.ipynb and flopy3_modpath7_structured_example.ipynb look like they are failing because the notebook kernel is set to python 2. I looked at the last couple of merges and these two notebooks failed there too. 

I'll check in the updates for 1) and 2) later today. I see that you pushed a fix for 3) today and will wait until it's merged to submit my changes.

**Comment by langevin-usgs** [comment]
I was able to fix your number (3) with the last PR, so if this passes now (by a manual inspection of the notebook run log on Travis) then we should be good to go...

**Comment by jlarsen-usgs** [comment]
Excellent, I'm running tests for 1) and 2) on my personal computer. Will commit this afternoon if everything passes on my machine.

**Comment by langevin-usgs** [comment]
Looks like there is one notebook still failing, but that one fails intermittently for some reason.  Thanks for all this @jlarsen-usgs.  Hopefully MODFLOW-NWT option handling issues are not put to rest...

**Pull request merged**
