### PR TITLE
draft checker structure

### PR DESCRIPTION
**Pull request by aleaf**
see <https://github.com/aleaf/flopy/blob/develop/examples/Notebooks/checker_demo.ipynb> for a description.

also added a working list of checks (<https://github.com/aleaf/flopy/blob/develop/checks.md>). Most of these are implemented, although the SFR checks need to be brought into the new framework described in the above notebook.

for some reason, does not pass test t004_test.py; the error occurs in the casting of the array attribute, and only for the model in this test case.

also does not pass t005_test.py. This appears to be an unstructured case, but the botm array in the DIS attribute has a shape of (1, 2, 2). Not sure how to relate the node index from stress_period_data to the botm array.

### CODE REVIEW

**Comment by langevin-usgs** [comment]
Andy can you fix your fork so that all the tests pass.  It is probably something simple.  Just go into the autotest folder and type "nosetests -v" from a command line interface.  We can't accept the pull request until everything is passing.

**Comment by aleaf** [comment]
Chris, I resolved the issue with t005, but still am not passing t004 because of this:
Any idea of what's going on?

```python
import flopy
import sys
sys.path.append('../autotest/')
from t004_test import stress_util2d

model_ws=''
ml = flopy.modflow.Modflow(model_ws=model_ws)
stress_util2d(ml, 1, 1, 1)

ml.lpf.vka.array


---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-b0a78e4fd225> in <module>()
----> 1 ml.lpf.vka.array

//anaconda/lib/python2.7/site-packages/flopy-3.2.3-py2.7.egg/flopy/utils/util_array.pyc in array(self)
    699         # for i,u2d in self.uds:
    700         for i, u2d in enumerate(self.util_2ds):
--> 701             a[i] = u2d.array
    702         return a
    703 

//anaconda/lib/python2.7/site-packages/flopy-3.2.3-py2.7.egg/flopy/utils/util_array.pyc in array(self)
   1854         # return a copy of self._array since it is being
   1855         # multiplied
-> 1856         return (self._array * cnstnt).astype(self.dtype)
   1857 
   1858     @property

//anaconda/lib/python2.7/site-packages/flopy-3.2.3-py2.7.egg/flopy/utils/util_array.pyc in _array(self)
   1872                 self.__value_built = \
   1873                     Util2d.load_txt(self.shape, file_in, self.dtype,
-> 1874                                     self.format.fortran).astype(self.dtype)
   1875                 file_in.close()
   1876             return self.__value_built

//anaconda/lib/python2.7/site-packages/flopy-3.2.3-py2.7.egg/flopy/utils/util_array.pyc in load_txt(shape, file_in, dtype, fmtin)
   1912                 istart = 0
   1913                 istop = width
-> 1914                 for i in range(npl):
   1915                     txtval = line[istart:istop]
   1916                     if txtval.strip() != '':

TypeError: range() integer end argument expected, got str.

**Comment by langevin-usgs** [comment]
Looks like there is an issue with util2d when changing to binary.  I modified the t004_test.py so that this issue would show up as a test fail.  Jeremy is going to take a look.

**Comment by langevin-usgs** [comment]
Andy, can you pull our changes into your fork and see if the tests pass now?

**Comment by langevin-usgs** [comment]
Andy, sorry about this, but can you pull in the latest changes from develop and resubmit the pull request?

**Pull request merged**
