### PR TITLE
MNW2 support

### PR DESCRIPTION
**Pull request by aleaf**
see notebook example in Notebooks folder for how it works.

still need to figure out how to properly cast the ```stress_period_data``` recarray to an mflist (for plotting and export to NetCDF). Right now I get this:

```python
m = flopy.modflow.Modflow('mnw2example', model_ws='temp')
dis = flopy.modflow.ModflowDis(nrow=5, ncol=5, nlay=3, nper=3, top=10, botm=0, model=m)
node_data = np.array([(0, 1, 1, 9.5, 7.1, 'well1', 'skin', -1, 0, 0, 0, 1.0, 2.0, 5.0, 6.2),
                      (1, 1, 1, 7.1, 5.1, 'well1', 'skin', -1, 0, 0, 0, 0.5, 2.0, 5.0, 6.2),
                      (2, 3, 3, 9.1, 3.7, 'well2', 'skin', -1, 0, 0, 0, 1.0, 2.0, 5.0, 4.1)],
                      dtype=[('index', '<i8'), ('i', '<i8'), ('j', '<i8'),
                             ('ztop', '<f8'), ('zbotm', '<f8'),
                             ('wellid', 'O'), ('losstype', 'O'), ('pumploc', '<i8'),
                             ('qlimit', '<i8'), ('ppflag', '<i8'), ('pumpcap', '<i8'),
                             ('rw', '<f8'), ('rskin', '<f8'), ('kskin', '<f8'),
                             ('zpump', '<f8')]).view(np.recarray)

stress_period_data = {0: np.array([(0, 0, 'well1', 0), (1, 0, 'well2', 0)],
       dtype=[('index', '<i8'), ('per', '<i8'), ('wellid', 'O'), ('qdes', '<i8')]).view(np.recarray),
                      1: np.array([(2, 1, 'well1', 100), (3, 1, 'well2', 1000)],
       dtype=[('index', '<i8'), ('per', '<i8'), ('wellid', 'O'), ('qdes', '<i8')]).view(np.recarray)}
mnw2 = flopy.modflow.ModflowMnw2(model=m, mnwmax=2, nodtot=3,
             node_data=node_data,
             stress_period_data=stress_period_data,
             itmp=[2, 2, -1], # reuse second per pumping for last stress period
             )
mfl = MfList(mnw2.stress_period_data, dtype=mnw2.stress_period_data[0].dtype, model=m)
mfl[1]
```
```
array([], shape=(0, 8), 
      dtype=(numpy.record, [('wellid', 'O'), ('qdes', '<f8'), ('capmult', '<i8'), ('cprime', '<f4'), ('hlim', '<f4'), ('qcut', '<i8'), ('qfrcmn', '<f8'), ('qfrcmx', '<f8')]))
```

### CODE REVIEW

**Comment by aleaf** [comment]
python 3.5 failed with this line:
```
t027_test.test_load ... /home/travis/build.sh: line 45:  6773 Segmentation fault      (core dumped) nosetests -v -w ./autotest
The command "nosetests -v -w ./autotest" exited with 139.
```
not sure what that means or how to fix it.

**Comment by langevin-usgs** [comment]
@aleaf can you isolate where the error is occurring?  I've never seen that one before.

**Comment by aleaf** [comment]
I can't see where the problem is occurring because it is only appearing in the Travis python 3.5 environment. ``t027_test.py`` runs fine with python 3.5 on my machine, both with numpy 1.9/matplotlib 1.4 and numpy 1.10/matplotlib1.5. I tried committing with different lines of code commented out. It runs the first block of ``test_load()``:

```python
    # load in the test problem (1 well, 3 stress periods)
    m = flopy.modflow.Modflow('MNW2-Fig28', model_ws=cpth)
    path = os.path.join('..', 'examples', 'data', 'mf2005_test')
    dis = flopy.modflow.ModflowDis.load(path + '/MNW2-Fig28.dis', m)
    mnw2 = flopy.modflow.ModflowMnw2.load(path + '/MNW2-Fig28.mnw2', m)
```
but then gets the segmentation fault in the second block. 
```python
    # load a real mnw2 package from a steady state model (multiple wells)
    m2 = flopy.modflow.Modflow('br', model_ws=cpth)
    path = os.path.join('..', 'examples', 'data', 'mnw2_examples')
    mnw2_2 = flopy.modflow.ModflowMnw2.load(path + '/BadRiver_cal.mnw2', m2)
    mnw2_2.write_file(os.path.join(cpth, 'brtest.mnw2'))
```

**Comment by jtwhite79** [comment]
I'm scared to suggest it, but maybe [https://github.com/pytest-dev/pytest-faulthandler](https://github.com/pytest-dev/pytest-faulthandler) would find something?

**Comment by aleaf** [comment]
I tried running ``t027_test.py`` on my Windows machine (python 3.5.1-2, numpy 1.10.1) and it was crashing with the dialog "Python stopped working." I tried stepping through in pycharm, but it seemed to be failing at inconsistent locations. I upgraded python to 3.5.1-4, and numpy to 1.11.0 and now t027_test.py runs with no errors there (as well as on my Mac).

I tried installing nose-faulthandler, but it said that it was included by default since python 3.2. I also installed pytest-faulthander, but it didn't seem to do anything when running the test with py.test.

Any ideas? Could this be a bug in older versions of python 3.5?

**Comment by jdhughes-usgs** [comment]
Any idea why t027 fails on python 3.5? Have you run it locally on your machine with 3.5?

**Comment by aleaf** [comment]
I haven't been able to reproduce the problem on either my mac or (windows) workstation. See note above.

**Comment by aleaf** [comment]
(both my mac and workstation have python 3.5.1)

**Comment by jdhughes-usgs** [comment]
travis looks like it is installing 3.5.0. Have you tried to create an environment with 3.5.0 rather than using 3.5.1?

**Comment by aleaf** [comment]
sorry, should have just done that earlier. The problem looks like a bug in python 3.5.0 though. The seg fault was occurring when running the ```recarry.sort()``` method on ```node_data```.

**Pull request merged**
