### PR TITLE
Revise SpatialReference properties, add geotransform

### PR DESCRIPTION
**Pull request by mwtoews**
The commit messages have more details, but the aim of this PR is to revise a few properties in the SpatialReference class. Here are the main changes:
 * Add `dx`, `dy`, `xlength`, `ylength` and `geotransform` properties to SpatialReference, which are used for array exports.
 * Remove `set_origin` and `theta`, as they don't appear to be needed (anymore?) and have no tests. They can be re-added, but some of the trigonometry will need to be revised, and tests added. `theta` was removed as it was using -ve angles for clockwise rotations. The correct rotation direction is counter clockwise (i.e. positive angles).
 * Exporting rasters with different resolutions in x- and y-directions should be supported by `export_array`, as it is supported by Surfer and GDAL (and hence QGIS). However, not all software support dx/dy in Arc Ascii grid formats. A warning is added if either delr and/or delc are not uniform.
 * Currently, rotated grids exported to Arc Ascii grids with `export_array` will do a spline interpolation. This modifies the grid dimensions and values, which are often extrapolated beyond the grid's min/max values. I've added a warning to be shown, as it's not typical that an export method would do this processing. Consider removing this feature, and moving the recipe to the Notes section or other place.

In case anyone is wondering where this is all going, I'd like to eventually revise `export_netcdf` to write netCDF files that are more compliant with the GDAL family of GIS software, which is best done with a `geotransform`.

Happy to discuss any of the changes, as there is a lot going on.

### CODE REVIEW

**Comment by spaulins-usgs** [comment]
Mike, a few of us are currently working on refactoring some of the SpatialReference code. We are generalizing the code so that the existing SpatialReference, exporting, and plotting code can be used with MODFLOW6. Specifically, we are adding a ModelGrid class with StructuredModelGrid and VertexModelGrid subclasses that handle model grid specific behavior.  SpatialReference will work with the different types of model grids to perform model grid specific operations, like get_xcenter_array.

That said, I briefly looked at your changes and I believe they can all be incorporated into what we are doing.  Andy Leaf may also have comments on this since he is the one currently working on the SpatialReference class. Given your interest and knowledge of the SpatialReference code I think it would be valuable if you reviewed our changes once we have completed them. Your input would be greatly appreciated.

**Comment by mwtoews** [comment]
@spaulins-usgs happy to review the mf6 spatial reference code, as these are critical components for exporting a variety of formats (rasters, netcdf, vtk, etc.). And yes, it does make sense to have subclasses, such as StructuredModelGrid, to handle mesh-specific properties such as the ones that I've touched in this PR.

**Comment by aleaf** [comment]
@mwtoews, I think this looks reasonable. I agree with @spaulins-usgs that all of these changes can be integrated into the upcoming revisions (see also https://github.com/modflowpy/flopy/issues/368 and let us know what you think). 

My only concerns are potentially adding to an already somewhat cluttered list of public attributes (but maybe this isn't that big of a deal) and also dx/dy when delr/delc have variable spacings. Instead of using median values, I think they should just be `None` or inactivated in some other way, to make it clear that they don't apply to that case.

**Comment by mwtoews** [comment]
As for dx/dy/geotransform returning `None` for non-uniform grids, I see the merit in this and I can change this behavior later today.

Also, considering #368, should the names dx/dy be renamed? In most other contexts, it seems that (e.g.) "x"/"y" means a projected coordinate, while here it means local Cartesian in model units. I can alternatively "hide" these properties as `_const_delr`, as they may not be helpful in too many other places.

**Comment by mwtoews** [comment]
I removed `dx` and `dy` to avoid the number of properties with "x" and "y", and replaced it with a single `resolution` property that returns a tuple of the model grid resolution with length multiplier applied.

Any other comments?

**Comment by mwtoews** [comment]
Closing this PR for now as it's based on deprecated methods. It may re-appear in a different form, as it would be useful to have an [Affine GeoTransform](https://www.gdal.org/gdal_datamodel.html) property for exporting regular grids to custom raster formats.

**Pull request closed without merging**
