### PR TITLE
fix(geometry): is_clockwise() now works as expected for a disv problem

### PR DESCRIPTION
**Pull request by emorway-usgs**

### CODE REVIEW

**Review by jlarsen-usgs — APPROVED** [review]
Changes look good. Automatic polygon closure was appending the incorrect vertex prior to this PR.

**Comment by langevin-usgs** [comment]
test?

**Comment by langevin-usgs** [comment]
In the future it would make more sense to add this test of a small function to an existing autotest script (such as t032_test.py which uses flopy.utils.geometry) instead of creating a new source file to test this small function.

**Comment by emorway-usgs** [comment]
I would be happy to move this new test over to t032 if helpful?  I was not aware other `flopy.util.geometry()` tests were being collected there.

**Pull request merged**
