### PR TITLE
feat(data storage): Data automatically stored internally when simulation or model relative path changed (#1126)

### PR DESCRIPTION
**Pull request by spaulins-usgs**
WARNING: This PR may break existing flopy for MF6 scripts that change simulation or model paths.  Data is now automatically stored internally when simulation or model paths are changed.  This is to greatly simplify the code for handling paths.  Data can be set back to external after changing paths, either individually, or by using the "set_all_data_external" method.

New simulation and model method "set_all_data_internal" added that sets all data internal. This method is automatically called whenever the simulation or model path are changed. This greatly simplifies flopy's behavior since flopy no longer needs to keep track of former and new external file paths that can possibly change multiple times before write is called.

### CODE REVIEW

**Comment by jdhughes-usgs** [comment]
@spaulins-usgs I am going to convert this PR to draft until you get the changes we talked about today implemented and we talk to @jtwhite79.

**Comment by jtwhite79** [comment]
Hey @spaulins-usgs - external files interacting with paths is hard!  I can see the value in loading everything into mem to help navigate this issue across a lot of use cases...so...here is a snippet that represents the standard operations we need to get the mf6 flopy support linked up with pyemu:

```sim = flopy.mf6.MFSimulation.load(sim_ws=org_model_ws)
    sim.simulation_data.mfpath.set_sim_path(tmp_model_ws)
    m = sim.get_model("freyberg6")
    sim.simulation_data.max_columns_of_data = m.dis.ncol.data
    sim.set_all_data_external()
    sim.write_simulation()
```
Can you check or make a test to ensure that the arrays that result from this are nrow X ncol and at the same dir level as the model input files?  Are the list-type input files still being written out as before in white space-delimited external files? Is the naming scheme for array and list external files that same?  We rely on that scheme in a lot of the pyemu testing...

Also, any chance to make the default `sim.simulation_data.max_columns_of_data = m.dis.ncol.data` internally to avoid the wrapped-format nightmare?

**Comment by spaulins-usgs** [comment]
@jtwhite79 The code changes I made should not effect array size, but I will double check this.  The main change is that when you call:

sim.simulation_data.mfpath.set_sim_path(tmp_model_ws)

All your data are automatically stored internally.  Though since you later call:

sim.set_all_data_external()

Your data are stored again externally.  I have introduced a test for this.  The external files are still written with the same formatting as before using the same naming scheme.

There is only one case that I know of where your code would result in a different outcome with my PR.  That case is where you already stored data externally in custom paths prior to calling "set_sim_path".  In this case my PR will set all your data internal.  This will then cause a different outcome when "set_all_data_external" is called since "set_all_data_external" by default leaves any existing external files alone, but the change in my PR sets all data internal so that all data is now affected by the "set_all_data_external" call and set to the default external file naming scheme.

For the "max_columns_of_data" default, I will make it ncol, though there are a few details worth stating.  First, this obviously will only be for models that use a structured grid.  Other models will still default to 20.  Flopy will set "max_columns_of_data" to ncol when loading a structured grid model or when a "dis" package is registered with a model.  This however will only happen if the user has not already manually set the "max_columns_of_data" property.   Also note that "max_columns_of_data" is a simulation-level setting.  For a simulation with two or more models that have a different ncol settings, "max_columns_of_data" will be set to the largest of the ncols.  I can look into the possibility of having a model-level "max_columns_of_data" setting as well, if this becomes an issue.

**Comment by jtwhite79** [comment]
That all sounds reasonable to me @spaulins-usgs .  Nice.

**Comment by spaulins-usgs** [comment]
@jdhughes-usgs Could you restart the checks?  They didn't restart with my last check-in because the PR was a draft.

**Comment by spaulins-usgs** [comment]
@jdhughes-usgs Two of the integration tests (windows 3.8 and windows 3.7) have had the status of "queued" for the last day.  Doesn't look like they will run.  Sorry to ask again, but can you restart the checks one more time?

**Pull request merged**
