### PR TITLE
Modified util_2d to use the OPEN/CLOSE control record when external_path is not specified

### PR DESCRIPTION
**Pull request by jbellino-usgs**
Modified `get_control_record()` and `get_file_array()` methods by creating
an additional condition to include cases where `external_path` (and
therefore `ext_filename`) has not been set and we have passed a file name
which we want opened and closed (not written to the destination package
file).

### CODE REVIEW

**Comment by jdhughes-usgs** [comment]
Jeremy can you take a look at these changes??

**Comment by jtwhite79** [comment]
I checked it out, but I couldn't get it to work with this code:
```
import os
import numpy as np
import flopy
model_ws = "model_ws"
if not os.path.exists(model_ws):
    os.mkdir(model_ws)
ml = flopy.modflow.Modflow(model_ws=model_ws)
nlay,nrow,ncol = 1,10,10
dis = flopy.modflow.ModflowDis(ml,nlay=nlay,nrow=nrow,ncol=ncol)
hk = np.ones((nrow,ncol))
# save hk up one dir from model_ws
np.savetxt("test.ref",hk)
#path to hk from where the model will be run
lpf = flopy.modflow.ModflowLpf(ml,hk=os.path.join("..","test.ref"))
ml.write_input()
```
It dies on the ```ml.write_input()``` because util_2d can't open "../test.ref".  I think its because python is running in a different location than where the model is going to run.  So we need to track file locations WRT both python and the model.  

Jason - I want to get this working.  Let's work on your branch then we can merge later.

**Comment by jbellino-usgs** [comment]
We could probably do something like `os.path.relpath("test.ref", model_ws)` where we point `flopy` to `test.ref` and then ensure that `ml.write()` uses the relative path from `model_ws`. I'll look at this more closely on Monday.

**Comment by jbellino-usgs** [comment]
In recognition of the fact that passed filenames are relative paths WRT `model_ws`, I added an `os.path.join(model_ws, value)` to ensure we are looking in the right place. This worked for Jeremy's test code as well as for my model where I run python from a subdir below `model_ws` and point MODFLOW to other subdirs to find input files.

**Comment by jbellino-usgs** [comment]
Working with Jeremy to incorporate this fix into several others. Closing request.

**Pull request closed without merging**
