### PR TITLE
refactor(setup/ci): require and test Python 3.5, 3.6, 3.7 and 3.8

### PR DESCRIPTION
**Pull request by mwtoews**
* Drop Python 2.7 <s>and 3.5</s> from test matrix; add Python 3.8
  * At this time, current fiona release does not compile with Python 3.8 (this will change with the next fiona version, however)
* Remove Python 2.7 requirements file/logic for install
* Simplify setup.py, raise RuntimeError if Python version too old
* Remove outdated comment (bdist_wininst is deprecated)
* Fix t007_test.py for Python 3.8, which raises other warnings (from matplotlib packages, also fixed for the next version)

### CODE REVIEW

**Comment by jdhughes-usgs** [comment]
@mwtoews What is the reason for dropping python 3.5? [The python 3.6.5 website](https://www.python.org/downloads/release/python-356/) indicates "https://www.python.org/downloads/release/python-356/". I imagine there are still people out there using 3.5 so unless there is functionality that is only available in 3.6 (and higher) that we want to use I would say we maintain testing for 3.5. What is your opinion of this?

Since you have started on the elimination of 2.7 support would you be willing to take on removing the checks for 2.7 in the code. I suspect the decrease in coverage is the result of not testing the version 2.7 conditionals.

**Comment by mwtoews** [comment]
@jdhughes-usgs opps, yes Python 3.5 support should stay for at least another year or two, as it does not have an end-of-life announcement yet ([PEP 478](https://www.python.org/dev/peps/pep-0478/)).

I've added a second commit to refactor the Python version checks throughout, as we can now assume nobody is using Python 2. Unfortunately, this does not change the coverage, which remains to be a mystery. The Codacy check can be ignored, as the only change to [Popen](https://docs.python.org/3/library/subprocess.html#popen-constructor) is to restore `close_fds` to use the default (this was only an odd issue with #623). The only remaining Python 2 feature to remove/refactor is the use of `next()`, which can be done later.

**Comment by jdhughes-usgs** [comment]
@mwtoews is this ready to merge?? The plan is to make another flopy release next week to coincide with the next MODFLOW 6 release. Will you have a chance to deal with the `next()` issue before then? The target release date is Dec 13-15.

**Comment by mwtoews** [comment]
@jdhughes-usgs I'd consider addressing `next()` as a not-so-simple low priority, which could be deferred or even ignored. Yes, this is ready to merge.

**Pull request merged**
