### PR TITLE
bug fix: segment renumbering

### PR DESCRIPTION
**Pull request by aleaf**
segments were being renumbering based on the nseg, outseg list from stress period 0, so subsequent stress periods where the segment data were listed differently were getting renumbered incorrectly. Also added sort to reach_data after it is renumbered so it is written consecutively to the SFR file.

### CODE REVIEW

**Comment by jdhughes-usgs** [comment]
Is this something that can wait until the next release (i.e., stay in the development branch for now) or is it a major problem for yesterday's release?

**Comment by aleaf** [comment]
It only matters if you have segment data (dataset 4) that varies by stress period (the number of segments listed varies, or they are listed in a different order) AND you want to renumber the segments so that the numbers only increase going downstream. I'm not sure how common this situation since it hasn't come up until now. If it's easy to include in the release, I'd say do it, but if it's a lot of hassle, maybe it can wait.

**Comment by jdhughes-usgs** [comment]
There are alot of steps in a release so I will leave it until the next release.

**Comment by jdhughes-usgs** [comment]
Is this something you want to add to the version 3.2.7 bug fix list in docs/version_changes.md

**Comment by aleaf** [comment]
Ok. Sorry I didn’t catch this earlier but sometimes it takes a while for the right (western) use case to roll in!

**Pull request merged**
