### PR TITLE
New vtk export functionalities

### PR DESCRIPTION
**Pull request by etiennebresciani**
* fix a few postprocessing and vtk export issues (1st commit)
* allow for selecting stress periods to export to vtk (2nd commit)
* allow for exporting to vtk as true 2d data (3rd commit)

### CODE REVIEW

**Comment by langevin-usgs** [comment]
@etiennebresciani, I was testing out some of the vtk stuff today, and for the most part it works really well!  One thing I noticed is that something is wrong with the kstpkper argument to functions like export_heads() (and others I think).  If passed in by the user, this should be a list of (kstp, kper) tuples.  The vtk export code seems to do all sorts of processing on this to come up with a kperlist and a kstplist, and then it iterates through those instead.  But this code doesn't work, and it seems overly complicated.  When it's time for the processing, can't we just do a loop like "for kstkp, kper in kstpkperlist:".  The looping right now does not work for me.  I suspect this is leftover code from before.  
And I have one small request.  For the export_heads() function, I'd like to be able to pass in some kwargs that are passed into the HeadFile constructor.  (for modflow 6 i'm working on transport that writes concentrations to a HeadFile-like file.). For example, I'd like to be able to be able to call:

    text = 'concentration'
    hds = HeadFile(hdsfile, text=text)

and then it would be nice if that text value was used to label the vtk data.  

Since your in the vtk code now, do you think you could look at these and add as part of this PR?

**Comment by etiennebresciani** [comment]
@langevin-usgs, I had a look at the issues you raised (but note that these are actually not related to what I did).

1. kstpkper argument: I also do not see the point of the processing on kstpkper. I removed it and now directly loop on kstpkper as you suggested. However, I do not think it will solve your problem. The code worked fine based on test t050 (functions test_vtk_binary_head_export() and test_vtk_cbc()), so not sure what is going wrong in your case.

2. I implemented your suggestion to add file opening options to the export_heads() function, and in fact also to the the export_cbc() function, to be consistent with HeadFile and CellBudgetFile classes, respectively. For the export_heads() function, now the code also use the 'text' argument in the file name and as the array name in the vtk file, as you suggested.

PS: I do not see any bad indentation at the lines indicated in Codacy review, so not sure what is going on here.

**Comment by langevin-usgs** [comment]
@etiennebresciani, thank you so much for doing that.  Your changes for kstpkper look much cleaner.  (I recognize that error wasn't due to your changes.).  I am seeing a double indentation following this line: https://github.com/modflowpy/flopy/blob/2cd8e1f2ee5eb3619ba2308568cf4bb44c7379d9/flopy/export/vtk.py#L1262, which may be the cause of the Codacy errors?

**Comment by etiennebresciani** [comment]
@langevin-usgs, so the changes I made removed the error you had? It made no difference in the t050 test cases.

Good catch about the line indents, which I forgot to delete after removing one level of for loop.

**Comment by langevin-usgs** [comment]
I didn't rerun my test, but the fix you implemented is identical to the fix that I had made locally.  The kstpkper looping that you fixed was a bit of a mess.  I'm surprised that it worked at all.  (And btw, at some point we should probably rethink the naming convention for those vtk head/budget output files so that they are more easily picked up by paraview.) Thanks so much for your contributions!  We really appreciate the thoroughly testing and clean code contributions.  Hopefully at some point we can get you to write a blog or provide some more helpful hints for using paraview to post-process MODFLOW models.

**Comment by etiennebresciani** [comment]
@langevin-usgs, oh, I think I know. Due to the two nested for loops, you would have run into a bug when not having the same number of time steps in different stress periods. The test case in t050 only has stress periods with one time step, so it was running fine.

I am glad you find my contributions useful. I will keep in mind the idea of providing hints to using Paraview in combination with FloPy at some point - though I am still myself novice at this stage!

**Pull request merged**
