### PR TITLE
fix(styles): platform evaluation for Linux was incorrect

### PR DESCRIPTION
**Pull request by jdhughes-usgs**

### CODE REVIEW

**Comment by jdhughes-usgs** [comment]
@wpbonelli I am surprised we haven't caught the issue with flopy.plot.styles on Linux before. `platform.platform` was being compared to `"linux"`, which as far as I can see is always `"Linux"`. Am I missing something?

**Comment by mwtoews** [comment]
Another "fix" would be to remove the extra path logic using two style files and just make one style file with a bunch of alternative names for "font.sans-serif". I.e., remove `usgsmap_linux.mplstyle` and `usgsplot_linux.mplstyle` and with the two remaining style files, define:
```
font.sans-serif: Arial, Liberation Sans
```
and maybe add other possible sans-serif fonts to choose. See [this file](https://matplotlib.org/stable/users/explain/customizing.html) for default styles.

**Review by wpbonelli — APPROVED** [review]
I'm surprised we haven't caught this too. I like your idea @mwtoews, maybe we come back to that

**Comment by jdhughes-usgs** [comment]
> Another "fix" would be to remove the extra path logic using two style files and just make one style file with a bunch of alternative names for "font.sans-serif". I.e., remove `usgsmap_linux.mplstyle` and `usgsplot_linux.mplstyle` and with the two remaining style files, define:
> 
> ```
> font.sans-serif: Arial, Liberation Sans
> ```
> 
> and maybe add other possible sans-serif fonts to choose. See [this file](https://matplotlib.org/stable/users/explain/customizing.html) for default styles.

This is a better approach since it simplifies things. Thanks for the suggestion @mwtoews

**Pull request merged**
