### PR TITLE
Mflist dataframes work

### PR DESCRIPTION
**Pull request by jbellino-usgs**
This pull request resolves comment https://github.com/modflowpy/flopy/issues/282#issuecomment-359836641 where getting dataframes from Mflist objects with certain model configurations (e.g. 0 stress in period 1 followed by non-zero stress in subsequent periods) and packages was not working correctly.

### CODE REVIEW

**Comment by jdhughes-usgs** [comment]
@jtwhite79 and @aleaf-usgs should this modification to the MFList pandas dataframe helper be merged in for flopy 3.2.9???

**Comment by jdhughes-usgs** [comment]
@jbellino-usgs can you pull in the latest develop commit to determine if this passes on travis

**Comment by aleaf** [comment]
@jbellino-usgs what is this request supposed to do?

**Comment by jbellino-usgs** [comment]
@aleaf I've updated the description for this pull-request. It came out of a comment I had made on issue #282.

**Comment by aleaf** [comment]
@jbellino-usgs thanks. @jdhughes-usgs sounds good to me, as long as the relevant tests pass.

**Comment by jdhughes-usgs** [comment]
I think we have solved all of the issues related to #282. Does #289 help out pandas users??

**Comment by jdhughes-usgs** [comment]
will merge #289 if tests pass.

**Comment by jbellino-usgs** [comment]
@jdhughes-usgs it helped out <i>this</i> pandas user!

**Comment by aleaf** [comment]
Yes. The `get_dataframe` method provides a quick and easy way to get all stress period data in one table, and also to get data for a single variable across stress periods, without redundancy (`squeeze=True` drops any periods where the values don't change.). I think currently the only internal use of this method is in `MfList.export`, if the keywords `sparse` or `squeeze` `=True`. In those cases it is used to reduce the export output to only include cells with stress period data for that BC, and to create an attribute table with values across stress periods (see the [export example](http://localhost:8888/notebooks/Documents/GitHub/flopy3/examples/Notebooks/flopy3_export.ipynb)).

**Pull request merged**
