### PR TITLE
fix(shapefile_utils) unstructured shapefile export (#1220)

### LINKED ISSUE #1220: Error when the export() is called through DISU object
When the export() is called, 
`disu_sub.export(r'output/test_grid.shp')`

```
The error below is received,
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_8752/1798900599.py in <module>
----> 1 disu_sub.export(r'output/test_grid.shp')

C:\Anaconda\envs\py3\lib\site-packages\flopy\pakbase.py in export(self, f, **kwargs)
    672         from flopy import export
    673 
--> 674         return export.utils.package_export(f, self, **kwargs)
    675 
    676     @staticmethod

C:\Anaconda\envs\py3\lib\site-packages\flopy\export\utils.py in package_export(f, pak, fmt, **kwargs)
    687     if isinstance(f, str) and f.lower().endswith(".shp"):
    688         shapefile_utils.model_attributes_to_shapefile(
--> 689             f, pak.parent, package_names=pak.name, **kwargs
    690         )
    691 

C:\Anaconda\envs\py3\lib\site-packages\flopy\export\shapefile_utils.py in model_attributes_to_shapefile(filename, ml, package_names, array_dict, **kwargs)
    320 
    321                     if a.array.shape == horz_shape:
--> 322                         array_dict[a.name] = a.array
    323                     else:
    324                         # array is not the same shape as the layer shape

TypeError: unhashable type: 'list'
```

### PR DESCRIPTION
**Pull request by cnicol-gwlogic**
Errors encountered when exporting to shapefile from unstructured models.
See https://github.com/modflowpy/flopy/issues/1220

* add unstructured clauses to export/shapefile_utils.py for static arrays
  (e.g. DISU, LPF, BAS6). More work needed for boundary conditions (MFList
  and transientlist data types - eg RIV/RCH/EVT packages)
* add test to t506.py to export mfusg unstructured model shapefiles

close #1220

### CODE REVIEW

**Comment by cnicol-gwlogic** [comment]
This check error is from netcdf in windows; I think you might need to upgrade your netcdf4 package or something, because my local tests (in windows latest with latest netcdf package) do not experience this. Details from the CI log:
======================================================================
ERROR: t027 test export of MNW2 Package to netcdf files
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda\envs\flopy\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "D:\a\flopy\flopy\autotest\t027_test.py", line 385, in test_export
    nc = netCDF4.Dataset(fpth)
  File "src\netCDF4\_netCDF4.pyx", line 2307, in netCDF4._netCDF4.Dataset.__init__
  File "src\netCDF4\_netCDF4.pyx", line 1925, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -51] NetCDF: Unknown file format: b'temp\\t027\\MNW2-Fig28.nc'

**Comment by langevin-usgs** [comment]
We'll take a look at that netCDF error.  The version used for Windows must have just changed.  The error is bringing down some of the other tests as well.

**Comment by langevin-usgs** [comment]
@cnicol-gwlogic, can you pull in develop and push again?  The unrelated netcdf issue should be fixed now.

**Review by langevin-usgs — APPROVED** [review]
Hey @cnicol-gwlogic, this looks pretty good.  I didn't run it locally, but I see the tests are passing.  Thanks for adding this!

**Comment by cnicol-gwlogic** [comment]
No worries @langevin-usgs. I have a feeling unstructured boundary condition export is still not quite there (maybe for mf6 too), but vtk export issue  #1228 could be related to that. I'll have a go at it when I next get a chance if that issue doesn't get sorted.

**Pull request merged**
