### PR TITLE
update(ModflowFlwob and ModflowHob): added "no_print", "options", and…

### PR DESCRIPTION
**Pull request by jbellino-usgs**
… "filenames" kwargs.

### CODE REVIEW

**Comment by jdhughes-usgs** [comment]
Any possibility of adding a test of this option to the HOBS autotest?

Not sure if there is a Flow OBS test...if not how about making one?

**Comment by jbellino-usgs** [comment]
Sure thing, Joe.

**Comment by jbellino-usgs** [comment]
@jdhughes-usgs , there is some behavior when loading a model that is causing a problem when specifying the name of an output data file. The scenario here is in test 041—I'm loading the simple model using the `load_only` kwarg to ignore the `HOB` package which has output specified on unit 51. However, even though the model skips loading of the `HOB` package, unit 51 is nonetheless scooped up into the `external_units` variable which causes the `mbase.add_output()` to default to using the output file name found in the namefile even when there is a user-specified name lines (350–354 of mbase.py). I don't want to rush through the code trying to determine what would be impacted by making a change here just to make this PR prior to the next flopy release so maybe this one should be left off for now.

**Comment by jbellino-usgs** [comment]
@jdhughes-usgs Here is a piece of the proposed code from mfhob.py that adds the user-specified filename to the list of output files:

```python
        if iuhobsv is not None:
            fname = filenames[1]
            model.add_output_file(iuhobsv, fname=fname,
                                  extension='hob.out', binflag=False,
                                  package=ModflowHob.ftype())
```
And below is a link to the `add_output_file()` code in mbase.py that we are feeding with the above:

https://github.com/modflowpy/flopy/blob/fa9ceda729641a351d0e78646dfe6bbf44c9afab/flopy/mbase.py#L346-L354

Specifying `iuhobsv` sets the `add_cbc` flag `True` and the code tests to see if the unit number exists in the list of external units (line 350). Even when skipping packages during model load using the `load_only` kwarg, the unit number of the external file listed in the namefile still gets read into `self.external_units` and causes `fname` to get reset to the file name found in the namefile (line 352).

The simplest fix might be to add a condition test after line 351 in mbase.py to avoid overwriting a user-supplied file name:

```python
        add_cbc = False
        if unit > 0:
            add_cbc = True
            # determine if the file is in external_units
            if abs(unit) in self.external_units:
                idx = self.external_units.index(abs(unit))
                if fname is None:
                    fname = os.path.basename(self.external_fnames[idx])
                binflag = self.external_binflag[idx]
                self.remove_external(unit=abs(unit))
```

**Comment by jdhughes-usgs** [comment]
@jbellino-usgs Looks like a good change. Does it break anything? You should merge the latest develop before making a pull-request with the change.

**Comment by jdhughes-usgs** [comment]
can you add `, exe_name=exe_name`

```
m = flopy.modflow.Modflow.load(modelname + '.nam', model_ws=pth, check=False,
                                   load_only=pkglst, verbose=False, exe_name=exe_name)
```

on line 216 and resubmit?

**Comment by jbellino-usgs** [comment]
> @jbellino-usgs The load is using the default mf2005.exe which does not exist on travis. exe_name is defined to me mf2005 on travis (no .exe extension).
> 
> It looks like just the one test failed.

Yeah, I see that on travis now. I have a few other failures here since I don't have pymake installed and mf6.exe is not in my path.

Additionally, the problem I noted above is encountered in an experimental version of t041.py I'm working on locally that separates the HOB and FLWOB tests from one another—it's because of this that the FLWOB test is importing a name file that's got the HOB external file and I'm seeing those path-related issues I described above; sorry, that was a bit confusing.

**Comment by jbellino-usgs** [comment]
@jdhughes-usgs Maybe I should just leave that thread alone for now, it's really a separate issue from the kwargs and filename stuff I was adding for FLWOBS and HOBS. Looks like travis is passing now with the fix you suggested.

**Comment by jdhughes-usgs** [comment]
@jbellino-usgs are you ok to merge this and you can keep going after the release?

**Comment by jbellino-usgs** [comment]
@jdhughes-usgs That sounds like a plan.

**Pull request merged**
