### PR TITLE
New ZoneBudget utility

### PR DESCRIPTION
**Pull request by jbellino-usgs**
Created new "zonbud" package with object class called "ZoneBudget" to aggregate budget information using an array of zones by interrogating the cell-by-cell budget file directly. Should add the SWI face flow terms, but has not yet been tested. Does not yet aggregate flow in constant head cells. Submitting to get feedback!

### CODE REVIEW

**Comment by jbellino-usgs** [comment]
This could also be tucked into the zonbud_util module already proposed. Needs more testing on SWI and addition of constant head cells to the flow accumulation logic.

**Comment by jbellino-usgs** [comment]
Proposed function "run_zonbud()" is now packaged together with the ZoneBudget class in a single utility: flopy\utils\zonbud.py

**Comment by langevin-usgs** [comment]
Jason, this is looking good.  But I have a couple of comments:

1.  Do you need to add all the freyberg files?  Can't you use the ones that are already in the repository?  Also, if you need to commit binary files (hds cbc, etc) to the repo, then our convention is to call them *.githds, *.gitcbc, etc.  If you need them for freyberg, then we should add them to the original freyberg folder.

2.  At this point, I don't think we want a pandas dependency.  Can you have your utility return a recarray instead?  There is some pandas being used, but it is always wrapped in a try/except.  But I think a recarray would be better at this time.

**Comment by jbellino-usgs** [comment]
Thanks for the feedback, Chris. I removed the portion of the notebook examples where we re-run the freyberg model...this is unnecessary to demonstrate the zonbud utilities. I instead copied the .cbc that was generated into the freyberg folder and renamed it .gitcbc. I also consolidated the example data into a single folder called `data\zonbud_ex`. There is no more dependency upon `pandas`, except in the example notebook zonbud_ex1 where we try to use it to view the output .csv file.

**Comment by langevin-usgs** [comment]
One last thing -- I like that you are making the zone budget calculations natively using Python.  There are some tricks to doing constant heads.  Did you happen to look into the ZONEBUDGET code to see how it is done there?  The "CONSTANT HEAD" list/array is used only to figure which cells are constant heads.  The flow right face, flow front, etc. are then used to calculate the CHD budgets.  At least that is how I remembered it.  Would be good to verify if you haven't already.

**Comment by jbellino-usgs** [comment]
Yeah, I derived the logic from Arlen's fortran code. I've carved the `CONSTANT HEAD` part out in the code, but haven't tested it yet since my model doesn't have any constant head cells to test with. On a side note, I just compared results from the Floridan SWI model (using the new zonbud executable from Joe) against the calculations made by this new utility. Everything matches well, except `GEN HEAD BOUNDS`. I've tested with a 2- and 4-zone array and each time there is only 1 zone for which I get significantly lower inflow/outflow. This needs some more testing to see where the problem is occurring.

**Comment by jbellino-usgs** [comment]
Made some changes to the structure of the ZoneBudget class and it's associated methods. The class is now instantiated without reading any cbc data and exposes some functions which can be used to interrogate the cbc object prior to using the "get_budget()" function to budget with a specified zone array for a specific time. Some functionality may be seen as duplicative or unnecessary (e.g. get_ssst_cbc_array(), which just calls the "get_data()" method of the CellBudgetFile object and returns a Full3D array for a given source/sink/storage term) and can be removed if so desired. The "run_zonbud()" utility now accepts a list of kstpkper for budget option "L".

**Comment by jbellino-usgs** [comment]
I think I've gotten this utility as far as I can for the time being. The constant head stuff is a little weird right now, but seems to work for non-SWI models. I say "seems" because there were some -1's in the freyberg ibound array that didn't have a corresponding .chd package that threw this utility off. ZoneBudget found these cells and summarized them, but did not get accumulated by the new utility. After removing these "stray" -1's, the 2 output files matched. All bets are off for SWI models and I'm not sure why they won't match. Hopefully this is a good start and will be useful. It would be great if someone can clean up my hack job and get the constant head stuff worked out.

**Pull request closed without merging**
