### PR TITLE
fix(mtuzf1): a user comment on same line as nuzgag not processed correctly

### PR DESCRIPTION
**Pull request by emorway-usgs**
When a single value (“funit”) and a user comment appear on line w/ nuzgag, wrong len() calculated

### CODE REVIEW

**Comment by jdhughes-usgs** [comment]
@jlarsen-usgs there seems to be an issue related to a change in `matplotlib/tri/tricontour.py` that is causing the `flopy3_mf6_BasicPlotting.ipynb` notebook to fail. This error also occured with pull request #610. Travis is now running matplotlib `3.1.1`. Could you take a look?

**Comment by jlarsen-usgs** [comment]
@jdhughes-usgs I will take a look into the matplotlib tricontour issue

**Comment by mwtoews** [comment]
the matplotlib issue is a regression that can be "fixed" with `matplotlib<=3.1.0`

**Comment by langevin-usgs** [comment]
@emorway-usgs, please update with latest develop and resubmit.  Notebook test should pass now.

**Comment by emorway-usgs** [comment]
@langevin-usgs Not sure if this just needs a manual restart, or if this is in fact an issue, but 2.7 fails, a number of errors in the log file hint at memory problems with the message: `OSError: [Errno 12] Cannot allocate memory`

Not sure why all but 2.7 pass?  

latest_fail

**Comment by langevin-usgs** [comment]
This has been a chronic problem with 2.7.  Haven't looked into the root cause; have been just restarting until it passes.  Should be almost time to cut 2.7 loose...

**Pull request merged**
