### PR TITLE
feat(generate_classes): create a command-line interface

### LINKED ISSUE #1629: feature: create packages() for MODFLOW 6 as a executable
**Is your feature request related to a problem? Please describe.**
There isn't a problem with `create packages()` but is relatively obscure.

**Describe the solution you'd like**
A `create packages()` executable like `get-modflow`. Options could be available to download definition files from specified releases or provide path to custom definition files. 

**Describe alternatives you've considered**
None other than using the current implementation `create packages()`.

**Additional context**
None

### PR DESCRIPTION
**Pull request by mwtoews**
This is a simple command-line interface for `generate_classes()` using the [`-m` switch](https://docs.python.org/3/using/cmdline.html#cmdoption-m) method with argparse, which is cleaner than using the `-c` command switch approach. E.g., compare:
```diff
- python -c 'import flopy; flopy.mf6.utils.generate_classes(ref="develop", backup=False)'
+ python -m flopy.mf6.utils.generate_classes --ref develop --no-backup
```
Built-in help is shown with `python -m flopy.mf6.utils.generate_classes -h`.

At this time, it is not added to `[project.scripts]` (like `get-modflow`) since this is generally a developer feature, not a user feature.

Also, not sure if this was overlooked from #1907, but the defaults to `generate_classes()` would always show:
> DeprecationWarning: branch is deprecated, use ref instead

This is resolved by swapping these defaults to `branch=None` and `ref="master"`.

Closes #1629

### CODE REVIEW

**Review by w-bonelli — APPROVED** [review]

**Comment by w-bonelli** [comment]
Thanks @mwtoews  I did overlook the defaults in 1907.

I wonder if this could see use beyond developers e.g. modelers beta testing unreleased versions of modflow6. Are there downsides to adding a project.scripts command besides occupying the name, e.g. `gen-classes` or `create-packages`?

**Comment by mwtoews** [comment]
There's no big downsides, it just creates several objects (e.g. an `.exe` wrapper for Windows). These do get cleaned-up with `pip uninstall flopy` too. My rationale on "why not" is that most users won't need it.

Calling modules in Python is pretty common (e.g. `python -m numpy.f2py -h`).

**Comment by mwtoews** [comment]
Another future consideration is to expose a top-level `flopy` command with sub-commands. E.g.

    $ flopy generate_classes -h

and I say future consideration, since there could be other potential sub-commands. A few ideas:

- `flopy info` to get basic information on a model
- `flopy plot` to generate plots from a model and/or simulation resullt

And probably others. You can see example sub-commands with `git -h` to get an idea of what I'm thinking.

**Comment by jdhughes-usgs** [comment]
@w-bonelli not sure if your recent CI changes impact this PR.

**Comment by w-bonelli** [comment]
I think this should not present any CI issues.

The top-level `flopy` command with subcommands seems nice from a user perspective and it would also disambiguate any overlap with non-flopy commands. Maybe before the next minor release that could be implemented for this and get-modflow.

**Pull request merged**
