### PR TITLE
Update CI testing workflow

### PR DESCRIPTION
**Pull request by w-bonelli**
This work-in-progress PR:

- adds a new pytest capability to automatically keep the outputs of failed tests
- adds a `-S` (`--smoke`) pytest CLI shortcut
- updates the testing workflow in `ci.yml`
- adds info on a few useful tools to dev docs
- marks a few flaky tests for retries
- adds benchmarks for modpath7 `PathlineFile` and `EndpointFile` utilities

## Automatically keeping test outputs

A new `--keep-failed` pytest CLI option is added in `conftest.py`. This works like `--keep` but keeps only failed test outputs, rather than all tests. This is used now in `ci.yml`.

## CI workflows

Workflows are now split into the following files:

- `commit.yml`
- `daily.yml`
- `mf6.yml`
- `rtd.yml`

The latter two are the same as before. Previously workflows were named according to platform. Workflows now contain jobs organized according to when they run. The commit workflow is triggered on commit, PR, etc as before. The cron workflow is triggered at 8am daily as before. Each workflow now contains jobs for all operating systems.

The commit workflow looks like this:

```mermaid
  flowchart TB;
      B["build (ubuntu-latest, Python3.7)"];
      L["lint (ubuntu-latest, Python3.7)"];
      S["smoke test (ubuntu-latest, Python3.7)"]-->T["test (ubuntu-latest, macos-latest, Python3.7-3.10)"] & W["test Windows (windows-latest, Python3.7-3.10)"];
```

Commit-triggered tests have been divided into smoke tests, which only run on Ubuntu Python3.7 and complete in a minute or two, and a regular test job, which runs all tests that aren't examples, regression or benchmarks, and uses matrices to run Python3.7-3.10 and all platforms in parallel. (Python3.10 has been added as a new testing target, previously only up to 3.9 was tested.) Regular tests only run if smoke tests pass.

(A new shortcut is added to the pytest CLI to run smoke tests: `pytest -S`, or `pytest --smoke` is now equivalent to `pytest -m "not slow and not example and not regression"`.)

Example scripts and notebooks, regression/comparison tests, and benchmarks are now defined in `daily.yml`. These also use matrices to test Python3.7-3.10. All these jobs run in parallel.

All test jobs save failed tests as an artifact, as before. The benchmark job saves an additional artifact with performance results. All test jobs use the new `--keep-failed` option described above to automatically save failed test outputs.

## Developer documentation

I added a section to `DEVELOPER.md` with some information about [doctoc](https://www.npmjs.com/package/doctoc) and [act](https://github.com/nektos/act). The former generate tables of contents for markdown files, and the latter allows testing GitHub actions workflows locally with docker.

## Flaky tests

The tests for the new `get-modflow` utility are a [bit](https://github.com/modflowpy/flopy/runs/7637313532?check_suite_focus=true#step:12:2103) [flaky](https://github.com/modflowpy/flopy/runs/7637313727?check_suite_focus=true#step:12:2533) due to some apparent inconsistencies in response returned by the github releases API. (E.g., `Release 'latest' not found -- choose from ['latest', ...]`). These are now marked for up to 3 retries, with a couple seconds backoff in case the issue is transient.

~~@mwtoews, any thoughts on how to address this? I guess `get-modflow` could retry when the github API returns something nonsensical. Would probably take some experimentation to see how often that happens and how many are sufficient?~~

**Update**: hopefully #1480 solves this. Will leave the test retries for a day or two and if the problem doesn't reappear will remove them.

## Benchmarks

Benchmark functions were added to `test_performance.py` for `PathlineFile.get_destination_pathline_data()`, which runs slowly for the model in the `flopy3_modpath_create_simulation.ipynb` example notebook (tracked [here](https://github.com/modflowpy/flopy/issues/1479)).

### CODE REVIEW

**Comment by langevin-usgs** [comment]
@w-bonelli, thanks for looking into the modpath notebook.  As this is a small simple model, it doesn't make sense that those destination path lines take so long to calculate.  We will need to look into a more efficient approach for this or determine if there is a bug.  Ideally those calculations for a simple model should take a few seconds.

**Comment by w-bonelli** [comment]
@langevin-usgs Ok, I will open an issue to keep tabs on the path line calculation concern. In the meantime I will try to figure out where in that function things slow down.

Will update this PR to put example scripts/notebooks and pymake comparison tests on a daily cronjob as discussed today. After that, unless there is further feedback I'll plan to mark this as ready for review.

**Comment by mwtoews** [comment]
Thanks for capturing a few stray outputs from get-modflow. Expect another PR that will internally retry to request.

**Comment by w-bonelli** [comment]
This is probably ready for a look but not quite for a merge. I did a little local testing for the scheduled CI jobs but`act` can only run linux images and doesn't perfectly reproduce the github environment so tomorrow morning is the real test.

**Review by jdhughes-usgs — APPROVED** [review]

**Pull request merged**
