### PR TITLE
feat: get modflow utility

### PR DESCRIPTION
**Pull request by mwtoews**
This new features adds a console program with FloPy `get-modflow` (or `get-modflow.exe` for Windows), which automates installing MODFLOW and related programs from GitHub releases hosted at https://github.com/MODFLOW-USGS/executables or https://github.com/MODFLOW-USGS/modflow6-nightly-build

Features:

- Easy way to install MODFLOW and related programs on Windows, Mac or Linux
- The utility can be used as a console program installed with FloPy, or as a flopy module (`flopy.utils.get_modflow_main`)
- The script can be downloaded separately from FloPy with CC0 license, and run as any basic Python script

Here is what `get-modflow --help` currently shows:
```
usage: get-modflow [-h] [--repo {executables,modflow6-nightly-build}] [--release-id RELEASE_ID]
                   [--ostag {linux,mac,win32,win64}] [--subset SUBSET] [--downloads-dir DOWNLOADS_DIR] [--force]
                   [--quiet]
                   bindir

Download and install USGS MODFLOW and related programs.

positional arguments:
  bindir                directory to extract executables; use '?' to help choose

optional arguments:
  -h, --help            show this help message and exit
  --repo {executables,modflow6-nightly-build}
                        name of GitHub repository; default is 'executables'
  --release-id RELEASE_ID
                        GitHub release ID (default: latest)
  --ostag {linux,mac,win32,win64}
                        operating system tag; default is to automatically choose
  --subset SUBSET       subset of executables
  --downloads-dir DOWNLOADS_DIR
                        manually specify directory to download archives
  --force               force re-download
  --quiet               show fewer messages
```

For example, if flopy is installed in a conda environment named "test", install the executables to that environment:
```
(test) C:\Users\mtoews>get-modflow ?
select a directory to extract executables:
 1: C:\Users\mtoews\AppData\Local\miniforge3\envs\test\Scripts
 2: C:\Users\mtoews\AppData\Local\Microsoft\WindowsApps
> 1
fetched release '8.0' from MODFLOW-USGS/executables
using previous download 'C:\Users\mtoews\Downloads\modflow_executables-8.0-win64.zip' (use '--force' to re-download)
file prms.exe does not exist
extracting 25 files to 'C:\Users\mtoews\AppData\Local\miniforge3\envs\test\Scripts'
crt.exe (1.3.1)         mflgrdbl.exe (2.0.0)    sutra.exe (3.0)
gridgen.exe (1.0.02)    mfnwt.exe (1.2.0)       swtv4.exe (4.00.05)
gsflow.exe (2.2.0)      mfnwtdbl.exe (1.2.0)    triangle.exe (1.6)
libmf6.dll (6.3.0)      mfusg.exe (1.5)         vs2dt.exe (3.3)
mf2000.exe (1.19.01)    mfusgdbl.exe (1.5)      zbud6.exe (6.3.0)
mf2005.exe (1.12.00)    mp6.exe (6.0.1)         zonbud3.exe (3.01)
mf2005dbl.exe (1.12.00) mp7.exe (7.2.001)       zonbudusg.exe (1.5)
mf6.exe (6.3.0)         mt3dms.exe (5.3.0)
mflgr.exe (2.0.0)       mt3dusgs.exe (1.1.0)
(test) C:\Users\mtoews>where mf6
C:\Users\mtoews\AppData\Local\miniforge3\envs\test\Scripts\mf6.exe
```
----
The documentation is in draft form at the moment, to gather feedback.

### CODE REVIEW

**Comment by jdhughes-usgs** [comment]
@w-bonelli can you take a look at this to see if it is compatible with the test refactoring you are doing?

**Comment by w-bonelli** [comment]
Looks awesome to me. I can rebase if this gets merged in first. There shouldn't be any conflicts.

@mwtoews , BTW I added your `requires_github` pytest marker to `conftest.py` as I found it useful for another test case. I can update your test script to pull it in from there when my PR is merged, if you like.

One question in my mind is how should flopy behave with this new capability? Should all executables be installed immediately when flopy is first installed? Or lazily, when they're needed? Or up to the user to manually run the install script?

Similarly, how does this affect assumptions about executable availability when testing? Currently we check if an exe is available and skip if not. I've preserved this in my refactor with a marker to indicate when an executable is needed, e.g. `requires_exe("mf2005")`. But if it's decided that the executables are a core part of the flopy install then I can remove the markers.

**Review by w-bonelli — APPROVED** [review]

**Comment by mwtoews** [comment]
@w-bonelli yes, re-use the components elsewhere in the pytest framework. The `requires_github` fixture might also need to consider that the macOS CI tests often get "HTTP Error 403: rate limit exceeded" due to a technical reason (something to do with their macOS VMs share a single MAC address for all GitHub users). The "HTTP Error 403" error can be captured and tests skipped.

As for new behavior, I don't think installing executables needs to be a pre-requisite for running pytest, since an internet connection is not always available (or "HTTP Error 403" is present). Fixtures like `requires_exe("mf2005")` are good. Encouraging developers to install executables should be encourage in the docs.

**Comment by w-bonelli** [comment]
> The "HTTP Error 403" error can be captured and tests skipped.

Added this to `test_scripts.py` in #1458. We could have `requires_github` check and skip if rate-limited, but I think it would consume a request for each decorated test [unless the user is authenticated](https://docs.github.com/en/rest/rate-limit) or we did some caching. For now I did it manually.

**Pull request merged**
