### PR TITLE
Fixed bug in zonbud utility that wasn't accumulating constant heads p…

### PR DESCRIPTION
**Pull request by jbellino-usgs**
…roperly. Cleaned up code and updated autotest. It should also be noted that the naming convention for budget records has changed from "XYZ_IN" to "FROM_XYZ" to align with the naming convention of the zonebudget executable program.

### CODE REVIEW

**Comment by jbellino-usgs** [comment]
@jdhughes-usgs and @langevin-usgs , I'm not sure what's up with Travis, but I keep getting random errors during environment build processes.

**Comment by jbellino-usgs** [comment]
Weird, the failure reversed itself and is now passing.

**Comment by jdhughes-usgs** [comment]
I restarted the build on the python version that was failing.

**Comment by jbellino-usgs** [comment]
Thanks Joe.

**Pull request merged**
