### PR TITLE
Fix(modflowpy#720): explicitly set shapefile record dtypes in write_grid_shapefile2

### PR DESCRIPTION
**Pull request by jlarsen-usgs**

### CODE REVIEW

**Comment by langevin-usgs** [comment]
@aleaf-usgs, can you look at this PR?

**Comment by aleaf** [comment]
@jlarsen-usgs thanks for submitting this. Can you make a small test to show that it works as expected? My only other comment after looking back over the `write_grid_shapefile2` code is that we're declaring dtypes in two places- above in creating the schema for the shapefile (`fieldinfo` variable) and then again below in the reformatting of the array input. It might be more robust to set up the schema and array dtypes in the same loop. This would make the intent of the code more explicit, and also help guarantee consistency between the dtypes in the schema and array input.

**Comment by jlarsen-usgs** [comment]
@aleaf 

I updated the `write_grid_shapefile2` code to remove redundancy and to guarantee consistency between the dtypes and the array input. I also added a couple lines of code to explicitly close polygons before they are passed to pyshp and added a test for this.

The other two issues are compatibility issues with pyshp v. 1.2.1 and were found by running the existing tests with a downgraded version of pyshp (t007_test.test_shapefile_ibound and t007_test.test_export_contourf). Would it be wise to have a one of the jobs on travis use pyshp 1.2.1 to cover these, since we are still supporting compatibility?

In addition, I found that `write_grid_shapefile` is not currently used by FloPy, however there is a single unit test that calls it. Do you think this method should be removed?

**Comment by aleaf** [comment]
If `write_grid_shapefile` is not being used, I see no reason not to get rid of it, and rename `write_grid_shapefile2` to take its place. Re: pyshp, I would say just drop support for version 1.21 and have travis run whatever the minimum requirement is.

**Comment by jlarsen-usgs** [comment]
@aleaf 
I've removed `write_grid_shapefile` and renamed `write_grid_shapefile2` to take its place. All support for pyshp 1.2.1 has been dropped in the latest commit.

**Comment by jlarsen-usgs** [comment]
Finished committing to this PR.

**Pull request merged**
