### PR TITLE
docs(mf6io): update .dfn files corresponding to similar change in mf6

### PR DESCRIPTION
**Pull request by emorway-usgs**
Not sure what's causing the failure in [MF6 #1356](https://github.com/MODFLOW-USGS/modflow6/pull/1356), maybe the discrepancy between the dfn files stored in mf6 vs what's here in flopy?

### CODE REVIEW

**Comment by langevin-usgs** [comment]
It's unclear to me why this PR is required for the MODFLOW 6 refactoring.  I think we should update the dfn files, but I think we typically do that when we make mf6 and flopy releases.

**Comment by wpbonelli** [comment]
@langevin-usgs I think updating flopy DFNs is needed as a consequence of #1824. Before that, the latest mf6 release was used for flopy CI tests. I believe we discussed at the time but I don't recall the full context. May be worth revisiting / reconsidering?

**Comment by emorway-usgs** [comment]
I was unaware the .dfn files get updated during the procedures leading up to a release.  I opened the PR as a matter of "house-keeping" with the thinking that the .dfn files should remain synchronized as development moves forward.

**Comment by wpbonelli** [comment]
IIRC, the [addition of an example model using develop features](https://github.com/MODFLOW-USGS/modflow6-examples/pull/98) prompted the move to keep mf6 and flopy DFNs in sync. I don't think this would be necessary if a develop/master branch release approach were adopted on the example repo.

**Comment by langevin-usgs** [comment]
@emorway-usgs, can you regenerate the flopy classes and include them in this PR?

**Comment by langevin-usgs** [comment]
It would probably be better if you only updated the classes relevant to this PR.

**Comment by emorway-usgs** [comment]
@langevin-usgs, agreed, have backed-out the adjustments that were made to the timestamps of the other classes not touched by this PR

**Review by langevin-usgs — APPROVED** [review]

**Pull request merged**
