### PR TITLE
Implement intersect method for VertexGrid

### PR DESCRIPTION
**Pull request by rubencalje**
I have implemented the intersect-method for a VertexGrid (disv). This intersect method is set up in the same way as in a StructuredGrid, where you pass floats `x` and `y` and optionally a variable called `local`, and you get a cell2d-number in return (instead of row,col).

This method first checks which cells are likely to intersect with the point (x,y), to speed things up. Then it uses the Path.contains_point method from matplotlib. It should work for any type of geometry (rectangles, triangles, etc.). When the point is on the edge between two cells, the lowest cell2d-number is returned.

I have added some lines in flopy3_mf6_vertex_plotting.ipynb, so that the code is tested. Please let me know it this is not the way to go.

### CODE REVIEW

**Comment by rubencalje** [comment]
It seems the intersect method of a StructuredGrid is broken. I always get nrow-1 and ncol-1. I will add a fix to my pull request,and a test to compare StructuredGrid and VertexGrid intersection. Is it ok if I put this test in a new file called t551_test.py?

**Comment by langevin-usgs** [comment]
@rubencalje, thanks for looking into this.  I think your intersection capabilities are general and can be used with newer and older versions of MODFLOW, so maybe it would be better to add a new test called t062_test_intersect.py.  We've been using the t5xx tests for MODFLOW 6, though there is no hard and fast rules on all of this.  I see that there is no intersect test at the moment, so it's no surprise that it's broken.  It would be great if you fix it.  Thanks!

**Comment by rubencalje** [comment]
For some strange reason, Python 2.7 fails on a memory error in Travis, on a completely unrelated test. Did you have this before?

**Comment by langevin-usgs** [comment]
We do get strange errors like that from time to time.  I'm going to go ahead and accept this PR.  Thanks for adding the test.

**Pull request merged**
