### PR TITLE
Feat(ModflowAg): Added ModflowAg package for NWT

### PR DESCRIPTION
**Pull request by jlarsen-usgs**
* added t071_test_nwt_ag.py to autotest

### CODE REVIEW

**Comment by jlarsen-usgs** [comment]
@langevin-usgs and @jdhughes-usgs 

The version of mf.py from my develop branch includes all recent changes (up to PR #908). I'm wary to resolve this personally, because it will commit some of the Ag Package changes into the flopy develop repo before the PR is accepted.

**Comment by jdhughes-usgs** [comment]
@jlarsen-usgs it is hard to see the changes because it looks like alot of the changes are line ending changes. I just merged a pull-request into develop that normalizes all of the line ending changes in the repo (except for the MODFLOW data files in the examples subdirectory). I added a `.gitattributes` to the repo that will make sure python files committed to the repo have the same line endings.

So to make it easier to see the changes could you.

1. Delete this current pull request. 
2. Copy out the new files and files that you actually modified.
3. Delete the develop branch on your fork and checkout the develop branch from upstream. This will get you a fresh copy of develop with the corrected line endings and all of your changes will have the correct line endings.
4. Add your files back in or reapply the changes to the existing files using a merge tool (KDIFF etc)
5. Resubmit the pull request. 

You should see that files you haven't changed won't be resubmitted as changed files.

I also noticed that you are submitting a relatively big example file. First question is can you build the files with flopy rather than adding them to the repo? If not, could you just save the model input files to the `examples/data/` subdirectory and for the test(s) copy the files to the `autotest/temp/mytest` subdirectory, load them with flopy, and then run to provide the baseline files? If you really need the output files we have been changing the extension to `.githds` and `.gitcbc`.

Sometime today or tomorrow the latest MODFLOW-NWT executable will be available from the github executables repo so we will be able to run the Ag package tests on travis.

Sorry for all of the trouble.

**Comment by jdhughes-usgs** [comment]
@jlarsen-usgs Could you reapply your recent changes from the replacement branch to this pull request?

**Comment by jlarsen-usgs** [comment]
@jdhughes 
Yes. I will do that this afternoon.

**Pull request closed without merging**
