### PR TITLE
fix(#2152): improve gridintersect geometry creation for vertex grids

### LINKED ISSUE #2152: bug: Grid intersect taking excessively long on simple voronoi grid
**Describe the bug**
The grid intersect routine is timing out on a relatively simple voronoi grid

**To Reproduce**

This script demonstrates the problem.  It creates a simple voronoi grid and plots it.  The next block, however, takes 2 mins on my computer, and doesn't finish in a reasonable amount of time if the grid if more finely discretized.

```
import pathlib as pl
import matplotlib.pyplot as plt
import numpy as np
from shapely.geometry import Polygon, LineString
import flopy
import flopy.utils.triangle
import flopy.utils.voronoi

ws = pl.Path('.')
tempdir = ws / "temp"
tempdir.mkdir(parents=True, exist_ok=True)

theta = np.arange(0.0, 2 * np.pi, 0.1)
radius = 80000.0
xoff = radius
yoff = radius
x = xoff + radius * np.cos(theta)
y = yoff + radius * np.sin(theta)
circle_poly = [(x, y) for x, y in zip(x, y)]

tri = flopy.utils.triangle.Triangle(maximum_area=2500**2, angle=30, model_ws=tempdir)
tri.add_polygon(circle_poly)
tri.build(verbose=False)

# And now for the voronoi grid
voronoi_grid = flopy.utils.voronoi.VoronoiGrid(tri)

fig = plt.figure(figsize=(5, 5))
ax = plt.subplot(1, 1, 1, aspect="equal")
voronoi_grid.plot(ax=ax, facecolor="none")
```

image

Now do some intersecting...

```
modelgrid = flopy.discretization.VertexGrid(**voronoi_grid.get_gridprops_vertexgrid(), nlay=1)
gi = flopy.utils.GridIntersect(modelgrid)

ls = LineString([p for p in circle_poly])
gi.intersects(ls)
```

**Expected behavior**
Seems like this intersection should only take a few seconds.  Note, that it would be nice to be able to change the maximum_area down to 1000**2.

### PR DESCRIPTION
**Pull request by dbrakenhoff**
improve performance _vtx_grid_to_geoms_cellids()

Fixes #2152.

### CODE REVIEW

**Comment by dbrakenhoff** [comment]
Question: how were these tests passing before? Im seeing VertexGrids being built directly from Triangle objects in the modflow6 tests in `test_prt_triangle.py` and `test_prt_ternary_methods.py`. Should that not be something along these lines?

```python
cell2d = tri.get_cell2d()
vertices = tri.get_vertices()

top = np.ones(tri.ncpl) * 1000.0
botm = np.ones((1, tri.ncpl)) * -100.0
idomain = np.ones((1, tri.ncpl), dtype=int)

triangular_grid = VertexGrid(
    vertices=vertices,
    cell2d=cell2d,
    idomain=idomain,
    nlay=1,
    ncpl=tri.ncpl,
    top=top,
    botm=botm,
)
```

**Comment by wpbonelli** [comment]
@dbrakenhoff that's on me &mdash; looks like those tests pass because `VertexGrid` doesn't validate the `vertices`  argument, the subsequent intersection returns empty, and the test doesn't try to use it in any case. I don't know how it ended up like that &mdash; maybe I wrote it assuming `VertexGrid` could take `Triangle` directly, or had a local copy of flopy modified to do so, and then decided not to use the intersection and forgot about it? I'll fix it on the mf6 side. Sorry and thanks for the catch!

**Comment by wpbonelli** [comment]
I also notice CI is doubled up here because this PR branch is on this repo, not a fork. Will fix that separately.

**Review by langevin-usgs — APPROVED** [review]

**Comment by dbrakenhoff** [comment]
> I also notice CI is doubled up here because this PR branch is on this repo, not a fork. Will fix that separately.

Ah my bad, I will submit PRs from my fork for future PRs! Thanks for fixing!

**Pull request merged**
