### PR TITLE
Add grid intersection functionality

### PR DESCRIPTION
**Pull request by dbrakenhoff**
Added grid intersection functionality and tests. See #536 
Grid intersection depends on shapely. 
Tests are written to pass if shapely is not found.
(Tests for triangular grid are also set to pass if no triangle_exe is defined at top of file.)

### CODE REVIEW

**Comment by dbrakenhoff** [comment]
Codacy somehow continues to think I'm importing MultiPolygon, even though the code shown on codacy doesn't contain any reference to MultiPolygon...

**Comment by langevin-usgs** [comment]
@dbrakenhoff, can you update this PR with the latest changes to develop.  Notebook test should pass with the update.

**Comment by dbrakenhoff** [comment]
Just the Python2.7 tests are failing now.

**Comment by langevin-usgs** [comment]
@dbrakenhoff, can you update and retry?  Would be good to get this settled for the next release.

**Comment by dbrakenhoff** [comment]
Still getting some errors unrelated to my PR for Python 2.7:
- [error] 0.01% t061_test_gridgen.test_gridgen: 0.1180s
```
ERROR: t061_test_gridgen.test_gridgen
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/dbrakenhoff/flopy/autotest/t061_test_gridgen.py", line 76, in test_gridgen
    g.build()
  File "/home/travis/build/dbrakenhoff/flopy/flopy/utils/gridgen.py", line 382, in build
    self._mkvertdict()
  File "/home/travis/build/dbrakenhoff/flopy/flopy/utils/gridgen.py", line 1761, in _mkvertdict
    format(fname))
Exception: File temp/t061/qtg.nod should have been created by gridgen.
-------------------- >> begin captured stdout << ---------------------
Error.  Failed to export polygon shapefile of grid []
Error.  Failed to export polygon shapefile of grid []
Error.  Failed to export usgdata []
Error.  Failed to export vtk file []
Error.  Failed to export shared vertex vtk file []
```
- [fail] 0.01% t048_test.test_mf2005fhbload('fhb.nam', '../examples/data/mf2005_test'): 0.1091s
```
FAIL: t048_test.test_mf2005fhbload('fhb.nam', '../examples/data/mf2005_test')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/dbrakenhoff/flopy/autotest/t048_test.py", line 70, in load_and_write_fhb
    assert success, 'new model run did not terminate successfully'
AssertionError: new model run did not terminate successfully
```
- [error] 0.01% t007_test.test_export_contourf: 0.1020s
```
ERROR: t007_test.test_export_contourf
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/dbrakenhoff/flopy/autotest/t007_test.py", line 1230, in test_export_contourf
    export_contourf(filename, cs)
  File "/home/travis/build/dbrakenhoff/flopy/flopy/export/utils.py", line 1184, in export_contourf
    level.append(levels[i])
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
-------------------- >> begin captured logging << --------------------
shapely.geos: DEBUG: Found GEOS DLL: <CDLL '/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/shapely/.libs/libgeos_c-bd8d3f16.so.1.10.2', handle b0774aa0 at 7f261e0b2e10>, using it.
shapely.geos: DEBUG: Trying `CDLL(libc.so.6)`
shapely.geos: DEBUG: Library path: 'libc.so.6'
shapely.geos: DEBUG: DLL: <CDLL 'libc.so.6', handle 7f2657bfa9e8 at 7f261e0b2e50>
```

**Comment by langevin-usgs** [comment]
@dbrakenhoff, there were a couple of accepted PRs that might help this.  Can you update and try again?  I think we're getting close...

**Comment by dbrakenhoff** [comment]
Updated and trying again!

**Comment by langevin-usgs** [comment]
Travis finally gave a thumbs up.  @dbrakenhoff, can you add a description of this functionality to https://github.com/modflowpy/flopy/wiki/FloPy-version-3.2.13-release-candidate-changes and close any issues that this addresses?  Thanks so much!  Looking forward to using these new capabilities.  I think they are going to be widely used.

**Comment by dbrakenhoff** [comment]
Added a description to the release notes. I can't close the issue(s) related to this PR though. I added a comment that #536 can be closed.

**Pull request merged**
