### PR TITLE
fix(ModflowUtllaktab): utl-lak-tab.dfn is redundant to utl-laktab.dfn

### PR DESCRIPTION
**Pull request by mwtoews**
[`utl-lak-tab.dfn`](https://github.com/modflowpy/flopy/blob/33e61b8ccd2556b65d33d25c5a3fb27114f5ff25/flopy/mf6/data/dfn/utl-lak-tab.dfn) is identical and redundant to [`utl-laktab.dfn`](https://github.com/modflowpy/flopy/blob/33e61b8ccd2556b65d33d25c5a3fb27114f5ff25/flopy/mf6/data/dfn/utl-laktab.dfn). Mf6io docs only refer to `'utl-laktab'`.

This file also caused a duplicate import in `flopy/mf6/modflow/__init__.py`

### CODE REVIEW

**Review by spaulins-usgs — APPROVED** [review]
@mwtoews, looks good.  Looks like createpackages.py was reading utl-laktab.dfn after utl-lak-tab.dfn and just writing over the "mfutllaktab.py" file created from utl-lak-tab.dfn with the file created from utl-laktab.dfn.  This is fortunate, since it means there is no need to rerun the createpackages utility.

**Comment by mwtoews** [comment]
A related curiosity is that sometimes [mfgwtgwt.py](https://github.com/modflowpy/flopy/runs/4960293040?check_suite_focus=true#step:10:221) (`ModflowGwtgwt`) gets generated, but I assume this is from modflow6 developments.

**Comment by langevin-usgs** [comment]
In the modflow6 repository under the autotest folder, there is an update_flopy.py script.  This script will replace the modflow 6 classes that come with flopy and create new classes that are generated with the current information in the modflow 6 repo.  This is how we keep flopy packages up to date with ongoing development in modflow 6.  When we make an official release, we formally update the flopy definition files and modflow 6 classes to correspond to those in the modflow 6 repo.  You are now seeing this ModflowGwtgwt class being generated in GitHub Actions because this is a new package that is in development in modflow 6.  We apologize for the bit of indirection here, but it allows the modflow development to dynamically harness flopy.

**Comment by langevin-usgs** [comment]
@spaulins-usgs, I think utl-lak-tab.dfn is an old version of the lake tables that we must have renamed.  Perhaps it didn't get removed when that information was last updated.

**Pull request merged**
