### PR TITLE
update(Notebooks): remove references to SpatialReference class

### LINKED ISSUE #1143: Notebooks that use SpatialReference need to be revised or rewritten
Flopy 3.3.5 is expected to remove several deprecated classes, including SpatialReference. This class is still documented in several notebooks (under `examples/Notebooks`):
- [flopy3_SpatialReference_demo.ipynb](https://github.com/modflowpy/flopy/blob/87ab682f3480e012336cb71166ffc8c5976009d1/examples/Notebooks/flopy3_SpatialReference_demo.ipynb) - this needs to be rewritten from scratch. A new notebook would ideally show how to use the `flopy.discretization` module, showing how to set spatial information to a modegrid, and how to use functions like `intersect` to query grid information.
- [flopy3_demo_of_modelgrid_classes.ipynb](https://github.com/modflowpy/flopy/blob/87ab682f3480e012336cb71166ffc8c5976009d1/examples/Notebooks/flopy3_demo_of_modelgrid_classes.ipynb) - probably only minor changes required
- [flopy3_MT3DMS_examples.ipynb](https://github.com/modflowpy/flopy/blob/87ab682f3480e012336cb71166ffc8c5976009d1/examples/Notebooks/flopy3_MT3DMS_examples.ipynb) - uses `.sr` property. Could these be rewritten to use `.mg` property?
- [flopy3_Modflow_postprocessing_example.ipynb](https://github.com/modflowpy/flopy/blob/87ab682f3480e012336cb71166ffc8c5976009d1/examples/Notebooks/flopy3_Modflow_postprocessing_example.ipynb) - also uses `.sr` property, to set rotation
- [flopy3_working_stack_demo.ipynb](https://github.com/modflowpy/flopy/blob/87ab682f3480e012336cb71166ffc8c5976009d1/examples/Notebooks/flopy3_working_stack_demo.ipynb) - another `.sr` property
- [flopy3_shapefile_export.ipynb](https://github.com/modflowpy/flopy/blob/87ab682f3480e012336cb71166ffc8c5976009d1/examples/Notebooks/flopy3_shapefile_export.ipynb) - briefly mentions "SpatialReference", but otherwise don't show any relevant code that will break.

Someone else more familiar with the discretization module classes will need to take on these tasks.

### PR DESCRIPTION
**Pull request by jlarsen-usgs**
* rewrote flopy3_demo_of_modelgrid_classes.ipynb to show most modelgrid features and usages 
* updated flopy3_Modflow_postprocessing_example.ipynb, flopy3_MT3DMS_examples.ipynb, flopy3_shapefile_export.ipynb, flopy3_working_stack_demo.ipynb
* removed flopy3_SpatialReference_demo.ipynb

* update(Grid.set_coord_info()): updated the merge_coord_info routine
* update(UnstructuredGrid()): added cross_section_vertices() override method 
close #1143

### CODE REVIEW

**Comment by jlarsen-usgs** [comment]
Here is a link to the new version of [flopy3_demo_of_modelgrid_classes](https://github.com/jlarsen-usgs/flopy/blob/develop/examples/Notebooks/flopy3_demo_of_modelgrid_classes.ipynb) if you'd like to look through it

**Comment by jlarsen-usgs** [comment]
@spaulins-usgs, 

Modflow-6 seems to be crashing on read for the API package. After investigating it looks likes flopy is not reading in or writing out the API package. Does this package need to be added to flopy?

**Comment by spaulins-usgs** [comment]
@jlarsen-usgs Looks like an API package DFN was added to the MF6 repository about 2 months ago.  That DFN can be used to update flopy so that it will read and write the new package.  The DFN found in the MF6 repository here

https://github.com/MODFLOW-USGS/modflow6/tree/develop/doc/mf6io/mf6ivar/dfn

needs to be copied into flopy here:

https://github.com/modflowpy/flopy/tree/develop/flopy/mf6/data/dfn

and then the createpackages.py script found here

https://github.com/modflowpy/flopy/tree/develop/flopy/mf6/utils

needs to be run to update flopy's interface.  Assuming the API package has a standard interface similar to the other packages, flopy should automatically start reading/writing the new package once you perform the above steps.  Once this is done and tested you can check in the dfn and the new package file(s) in flopy/mf6/modflow (generated by createpackages.py), and the updated __init__.py file.

**Comment by jlarsen-usgs** [comment]
Thanks @spaulins-usgs. I'll grab the dfn, test it out, and reach out if I have any issues generating the new package.

**Comment by jlarsen-usgs** [comment]
Added the API package support to this PR.

**Review by mwtoews — APPROVED** [review]
Changes (from what I can see) look good! Notebooks are tricky to see full diff outputs, so I can't say I saw 100% of everything.

**Pull request merged**
