### PR TITLE
update(mfsfr2, mfuzf1) change default optionblock behavior to block = True for 'nwt' models

### PR DESCRIPTION
**Pull request by jlarsen-usgs**
issue #942

### CODE REVIEW

**Comment by jdhughes-usgs** [comment]
@jlarsen-usgs Does this change essentially upgrade the uzf and sfr files to use the new options block? If so would this cause a problem for users that still wanted to use a version of NWT prior to the version where the options block was implemented?

**Comment by jlarsen-usgs** [comment]
@jdhughes-usgs this changes the default behavior when someone builds a new UZF or SFR package with flopy to use the options block if the model version is set to 'mfnwt'. A user can flip it back to line based options by specifying 
```
uzf.options.block = False
```

This change does not change the behavior of loading existing packages. If options are read in from an option line, we still maintain the option line format. Same with block format. 

The current behavior of the option block assumes option line when a user builds a new UZF or SFR package. The user can flip this to an option block by:

```
uzf.options.block = True
```

Thoughts on which would be the better default?

**Comment by jdhughes-usgs** [comment]
@jlarsen-usgs seems good to me. Just wasn't sure if it would change the behavior when loading existing models. I will merge unless you tell me to wait.

**Comment by jlarsen-usgs** [comment]
@jdhughes-usgs it is good to merge

**Pull request merged**
