### PR TITLE
Allow Stress Periods Beyond Nper (#694) and Allow Setting Simulation Name File Options on Init (#704) 

### PR DESCRIPTION
**Pull request by spaulins-usgs**
feat(#694): When stress packages have data for periods beyond nper flopy now issues a warning message (flopy use to raise an exception).

feat(#704): Allow user to set simulation name file options while initializing a simulation.

### CODE REVIEW

**Comment by spaulins-usgs** [comment]
Travis failed because of the the intermittent problems we have been seeing with deepcopy on python 3.5. I am looking into this problem now. The problem is very intermittent so I am not 100% sure I found the cause, though it looks like it has to do with MFChildPackages overriding __getattribute__ and __getattr__. I have had problems with deepcopy and __getattribute__ in the past. I am not sure I can reproduce the current dynamic interface without __getattribute__ though I will try to find another way to do this.

**Comment by langevin-usgs** [comment]
What happens if there is trash at the end of the file, such as comments or other information that the user does not expect to have read?  Will this cause flopy to crash? MODFLOW won't read that information.

**Comment by spaulins-usgs** [comment]
As long as the trash at the end of the file is outside of any block (not between a "begin" and "end" keyword) flopy will ignore it and not crash. If the trash is within a block or contains a line that starts with the "begin" keyword, flopy may report an error depending on the situation.

**Comment by langevin-usgs** [comment]
Then that will mean that flopy would die reading a file that MODFLOW can read.

**Comment by spaulins-usgs** [comment]
I tested flopy and it will only report an error if "begin" is at the beginning of a line and is followed by a valid block name in the trash text. So for,

_begin period trash text 
ewifojweoj fewoijfewoij_

flopy will report an error while for,

_begin trash text
ewfiojfewio ewf_

flopy will not report an error. I can fix the error though this is a really unlikely scenario where the user explicitly defines a specific block type as part of junk text. In cases like this I would think the majority of the time this would be a result of the end of the user's file getting messed up and the user should be notified of this.

**Pull request merged**
