### PR TITLE
another fix for uzf1 load with 'nwt_11_fmt'

### PR DESCRIPTION
**Pull request by MJKnowling**
`nwt_11_fmt` attribute now handled in uzf1 load

### CODE REVIEW

**Comment by langevin-usgs** [comment]
@MJKnowling can you add a docstring for nwt_11_fmt?  I was assuming that it was related somehow to the version number but we are on NWT 1.1.4 so I'm thinking I was wrong about that.  But it would be good for you tell us exactly what it means and what it means to be True or False.  Thanks.

**Comment by MJKnowling** [comment]
@langevin-usgs Absolutely! Apologies for overlooking this. My understanding of `nwt_11_fmt` is based on the description given for uzf1 dataset 1a here: https://water.usgs.gov/nrp/gwsoftware/modflow2000/MFDOC/index.html?uzf_unsaturated_zone_flow_pack.htm

Basically, as I understand it, setting the `nwt_11_fmt` argument to `True` means that the optional variables (e.g., `SPECIFYTHTR`, `SPECIFYTHTI`, `NOSURFLEAK`) are written in the “newer” format, i.e., line-by-line, following the keyword ‘options’ (and terminated by ‘end’). Note that setting `nwt_11_fmt = True` also supports some newer optional variables (e.g., `SPECIFYSURFK`, `REJECTSURFK`, `SEEPSURFK`) that are not supported pre-v1.1. If `False`, the optional variables are written in a specific order on a single line.

I have added a docstring with words to this effect. I also noticed the link to the Online Guide was superseded. Let me know if you’d like me to add anything else.

To be clear, when loading a uzf package file utilising `nwt_11_fmt` previously, this attribute was lost. `nwt_11_fmt` was always False. 

The benefit of the test I added to t034_test.py in the last PR (#349 ) is now better realised. There are still some uzf1 option combinations to hit with those tests though.

**Comment by langevin-usgs** [comment]
@MJKnowling quick question.  Do you know if we have to have the nwt_11_fmt variable as an argument?  Can't flopy detect this automatically?  If there are these additional newer variables specified by the user, then shouldn't flopy have to write the options block?  Likewise, if upon a load an options block is detected, then shouldn't this variable automatically be set to True?  I admit that I haven't looked much at this and so this is just off the top of my head, but it seems like maybe we could hide some of this from the user and have Flopy be a little smarter.  Just a thought, and maybe that's not possible for some other reason.  I thought maybe you were the one that originally implemented the nwt_11_fmt variable, but it sounds like that might not be the case.

**Comment by MJKnowling** [comment]
@langevin-usgs Agreed. We don't need it as an arg for loading purposes. It looks like it is required for writing though, due to the changes in mfnwt v1.1 regarding uzf1 options formatting, even if no newer variables are specified. So don't think it can be omitted from the writing step. I'm all for a "smarter" flopy, reducing the burden on the user as much as possible. I will get onto this in the next day or so.

**Comment by MJKnowling** [comment]
@langevin-usgs Sorry for delay - this one slipped under the radar. The `nwt_11_fmt` arg is already "hidden" from the user for loading (for reasons you describe). But, unfortunately, it is currently required for constructing `ModflowUzf1` because `nwt_11_fmt` cannot be assigned properly on the basis of new variables alone, e.g., see the test I added where none of the new features are used but the formatting is in the new style. So I think this is all we can do for now. It would probably make more sense to address this mfnwt end actually..

**Pull request merged**
