### PR TITLE
feat(multiple package instances): FloPy support for multiple instances of the same package stored in dfn files (#1239)

### PR DESCRIPTION
**Pull request by spaulins-usgs**

### CODE REVIEW

**Comment by langevin-usgs** [comment]
@spaulins-usgs, we need to make sure these changes are made to the definition files in the mf6 repo, otherwise these changes will get clobbered.

**Comment by spaulins-usgs** [comment]
@langevin-usgs Is that is happening with the integration tests?  Are the integration tests replacing the Flopy dfns with the MF6 ones?  I can't figure out why the integration tests are failing here while the tests work fine on my machine.  The integration test failures though are consistent with the tests using the old dfn files.

Anyway, I already have the changes ready to go for MF6 here:

https://github.com/spaulins-usgs/modflow6

I was going to submit a PR for MF6 the once all the tests passed for the Flopy PR.  However, perhaps I should be doing it the other way around.

**Comment by langevin-usgs** [comment]
Hey @spaulins-usgs, yes, I suspect the integration tests are rebuilding the MODFLOW 6 classes with the definition files from the MODFLOW 6 repository.  And keep in mind that the definition files in the MODFLOW 6 development branch are probably a little ahead of the ones in the flopy repo, so please make sure you don't accidentally lose changes.

**Comment by spaulins-usgs** [comment]
@langevin-usgs I submitted a PR for the MODFLOW 6 repository where I added the "# flopy multi-package" lines to the MF6 dfns (I didn't copy over them, just modified them, so no changes will be lost).  Once you accept/merge the MF6 PR please restart the checks on this PR to see if that fixes the failed checks.

**Comment by langevin-usgs** [comment]
@spaulins-usgs, can you update this PR with my latest changes?  It should hopefully pass after that.

**Comment by spaulins-usgs** [comment]
@langevin-usgs, I did an upstream merge which included both your changes and Josh's changes.  Looks like test_voronoi_grid5 is now passing but test_voronoi_grid2 is still a problem.  Also, there are some new errors importing rasterio and installing gdal on windows.

**Pull request merged**
